//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernDev.InTouch.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockJsonResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockJsonResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernDev.InTouch.Tests.MockJsonResponses", typeof(MockJsonResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;found&quot;:[{&quot;id&quot;:16133651,&quot;first_name&quot;:&quot;Vitalik&quot;,&quot;last_name&quot;:&quot;Ulybin&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;domain&quot;:&quot;ylubin&quot;,&quot;screen_name&quot;:&quot;ylubin&quot;,&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10feb\/bemQ80NlFWM.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fea\/5xmjTRE-1Bg.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe9\/BInBMF-GmS8.jpg&quot;,&quot;photo_200_orig&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe7\/sHgM2UkEh2o.jpg&quot;,&quot;has_mobile&quot;:1,&quot;wall_comments&quot;:0,&quot;can_post&quot;:0,&quot;can_s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string accountContacts {
            get {
                return ResourceManager.GetString("accountContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;friends&quot;:733,&quot;messages&quot;:21,&quot;gifts&quot;:2,&quot;app_requests&quot;:1}}.
        /// </summary>
        internal static string accountCounters {
            get {
                return ResourceManager.GetString("accountCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;country&quot;:&quot;UA&quot;,&quot;https_required&quot;:1,&quot;own_posts_default&quot;:1,&quot;no_wall_replies&quot;:1,&quot;intro&quot;:0,&quot;lang&quot;:0}}.
        /// </summary>
        internal static string accountInfo {
            get {
                return ResourceManager.GetString("accountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;id&quot;:456239447,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Ghastly&quot;,&quot;title&quot;:&quot;Get On This (Ghastly x Ablaze VIP)&quot;,&quot;duration&quot;:249,&quot;date&quot;:1460490199,&quot;url&quot;:&quot;https://cs7-4v4.v...WnpkZxdJH-KkPfxRvmQ&quot;}}.
        /// </summary>
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:15,&quot;items&quot;:[{&quot;id&quot;:71581179,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;Future House&quot;},{&quot;id&quot;:48731778,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;Laidback Luke&apos; Mixsmash Radio&quot;},{&quot;id&quot;:48731762,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;W&amp;amp;W&apos; Mainstage&quot;}]}}.
        /// </summary>
        internal static string audioAlbumItemsList {
            get {
                return ResourceManager.GetString("audioAlbumItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:6000,&quot;items&quot;:[{&quot;id&quot;:456239447,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Ghastly&quot;,&quot;title&quot;:&quot;Get On This (Ghastly x Ablaze VIP)&quot;,&quot;duration&quot;:249,&quot;date&quot;:1460490199,&quot;url&quot;:&quot;https://cs7-4v4.v...WnpkZxdJH-KkPfxRvmQ&quot;},{&quot;id&quot;:456239446,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Ghastly &amp; Mija&quot;,&quot;title&quot;:&quot;Crank It (feat. Lil Jon) vk.com/itunesmusic_inc&quot;,&quot;duration&quot;:255,&quot;date&quot;:1460463175,&quot;url&quot;:&quot;https://psv4.vk.m...zrOW_RuTa6p6a_IjH7Q&quot;,&quot;genre_id&quot;:2},{&quot;id&quot;:456239445,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Eptic &amp; Habstrakt&quot;,&quot;title&quot;:&quot;On The [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string audioItemsList {
            get {
                return ResourceManager.GetString("audioItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:456239447,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Ghastly&quot;,&quot;title&quot;:&quot;Get On This (Ghastly x Ablaze VIP)&quot;,&quot;duration&quot;:249,&quot;date&quot;:1460490199,&quot;url&quot;:&quot;https://cs7-4v4.v...WnpkZxdJH-KkPfxRvmQ&quot;},{&quot;id&quot;:456239446,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Ghastly &amp; Mija&quot;,&quot;title&quot;:&quot;Crank It (feat. Lil Jon) vk.com/itunesmusic_inc&quot;,&quot;duration&quot;:255,&quot;date&quot;:1460463175,&quot;url&quot;:&quot;https://psv4.vk.m...zrOW_RuTa6p6a_IjH7Q&quot;,&quot;genre_id&quot;:2},{&quot;id&quot;:456239445,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Eptic &amp; Habstrakt&quot;,&quot;title&quot;:&quot;On The Block (Blvk Sheep x S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string audioList {
            get {
                return ResourceManager.GetString("audioList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;lyrics_id&quot;:2428970,&quot;text&quot;:&quot;I&apos;ve got a mission A magic to perform, This rite of passage, Like the riders of the storm.&quot;}}.
        /// </summary>
        internal static string audioLyrics {
            get {
                return ResourceManager.GetString("audioLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;sid&quot;:&quot;super_sid&quot;,&quot;success&quot;:1,&quot;uid&quot;:12345}}.
        /// </summary>
        internal static string authStatus {
            get {
                return ResourceManager.GetString("authStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:65596623,&quot;name&quot;:&quot;FTP&quot;,&quot;screen_name&quot;:&quot;ftp78&quot;,&quot;is_closed&quot;:0,&quot;type&quot;:&quot;page&quot;,&quot;description&quot;:&quot;Чёрный юмор&quot;,&quot;members_count&quot;:341049,&quot;start_date&quot;:19450509,&quot;can_post&quot;:0,&quot;can_see_all_posts&quot;:1,&quot;activity&quot;:&quot;Art and entertainment&quot;,&quot;status&quot;:&quot;иди сюда&quot;,&quot;contacts&quot;:[{&quot;user_id&quot;:171605462,&quot;desc&quot;:&quot;Агент по рекламе &quot;},{&quot;user_id&quot;:313566042,&quot;desc&quot;:&quot;только Реклама . вп не делаем &quot;},{&quot;user_id&quot;:236428820}],&quot;can_upload_doc&quot;:0,&quot;can_upload_video&quot;:0,&quot;can_create_topic&quot;:0,&quot;fixed_post&quot;:1063983,&quot;verified&quot;:0,&quot;site&quot;:&quot;&quot;,&quot;main_a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string broadcastList {
            get {
                return ResourceManager.GetString("broadcastList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:18,&quot;items&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Агрохимии&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;Биофизики&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;Биохимии&quot;},{&quot;id&quot;:4,&quot;title&quot;:&quot;Ботаники&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Генетики и биотехнологии&quot;}]}}.
        /// </summary>
        internal static string chairsItemsList {
            get {
                return ResourceManager.GetString("chairsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;token&quot;:&quot;super_token&quot;,&quot;secret&quot;:&quot;super_secret&quot;}}.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:18,&quot;items&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Москва&quot;,&quot;important&quot;:1},{&quot;id&quot;:2,&quot;title&quot;:&quot;Санкт-Петербург&quot;,&quot;important&quot;:1},{&quot;id&quot;:10,&quot;title&quot;:&quot;Волгоград&quot;},{&quot;id&quot;:37,&quot;title&quot;:&quot;Владивосток&quot;},{&quot;id&quot;:153,&quot;title&quot;:&quot;Хабаровск&quot;}]}}.
        /// </summary>
        internal static string citiesItemsList {
            get {
                return ResourceManager.GetString("citiesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Москва&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;Санкт-Петербург&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;&quot;},{&quot;id&quot;:4,&quot;title&quot;:&quot;Herzliya&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Отрадное&quot;}]}.
        /// </summary>
        internal static string citiesList {
            get {
                return ResourceManager.GetString("citiesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot; : {
        ///		&quot;count&quot; : 20490,
        ///		&quot;items&quot; : [{
        ///				&quot;id&quot; : 85995,
        ///				&quot;from_id&quot; : 7219163,
        ///				&quot;date&quot; : 1459494929,
        ///				&quot;text&quot; : &quot;Здравствуйте.&quot;,
        ///				&quot;likes&quot; : {
        ///					&quot;count&quot; : 0,
        ///					&quot;user_likes&quot; : 0,
        ///					&quot;can_like&quot; : 1
        ///				},
        ///				&quot;attachments&quot; : [{
        ///						&quot;type&quot; : &quot;photo&quot;,
        ///						&quot;photo&quot; : {
        ///							&quot;id&quot; : 410545563,
        ///							&quot;album_id&quot; : -12,
        ///							&quot;owner_id&quot; : -1,
        ///							&quot;user_id&quot; : 100,
        ///							&quot;photo_75&quot; : &quot;https://pp.vk.me/...9bb/cC1ndaaUcag.jpg&quot;,
        ///							&quot;photo_130&quot; : &quot;https://p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commentItemsList {
            get {
                return ResourceManager.GetString("commentItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:234,&quot;items&quot;:[{&quot;id&quot;:19,&quot;title&quot;:&quot;Австралия&quot;},{&quot;id&quot;:20,&quot;title&quot;:&quot;Австрия&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Азербайджан&quot;},{&quot;id&quot;:21,&quot;title&quot;:&quot;Албания&quot;},{&quot;id&quot;:22,&quot;title&quot;:&quot;Алжир&quot;}]}}.
        /// </summary>
        internal static string countriesItemsList {
            get {
                return ResourceManager.GetString("countriesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Россия&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;Украина&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;Беларусь&quot;},{&quot;id&quot;:4,&quot;title&quot;:&quot;Казахстан&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Азербайджан&quot;}]}.
        /// </summary>
        internal static string countriesList {
            get {
                return ResourceManager.GetString("countriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:775,&quot;items&quot;:[{&quot;id&quot;:437429925,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;file.gif&quot;,&quot;size&quot;:428000,&quot;ext&quot;:&quot;gif&quot;,&quot;url&quot;:&quot;https:\/\/vk.com\/doc16815310_437429925?hash=1fb22b7ab82e2eb4f1&amp;dl=1460677884646710e77e68f9dffa&amp;api=1&quot;,&quot;date&quot;:1460580469,&quot;type&quot;:3,&quot;preview&quot;:{&quot;photo&quot;:{&quot;sizes&quot;:[{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c615129\/u344052\/-3\/m_56d17ef819.jpg&quot;,&quot;width&quot;:130,&quot;height&quot;:100,&quot;type&quot;:&quot;m&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c615129\/u344052\/-3\/s_56d17ef819.jpg&quot;,&quot;width&quot;:100,&quot;height&quot;:75,&quot;type&quot;:&quot;s&quot;},{&quot;src&quot;:&quot;https:\/\/pp.v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string docsItemsList {
            get {
                return ResourceManager.GetString("docsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:437429925,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;file.gif&quot;,&quot;size&quot;:428000,&quot;ext&quot;:&quot;gif&quot;,&quot;url&quot;:&quot;https:\/\/vk.com\/doc16815310_437429925?hash=1fb22b7ab82e2eb4f1&amp;dl=1460677884646710e77e68f9dffa&amp;api=1&quot;,&quot;date&quot;:1460580469,&quot;type&quot;:3,&quot;preview&quot;:{&quot;photo&quot;:{&quot;sizes&quot;:[{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c615129\/u344052\/-3\/m_56d17ef819.jpg&quot;,&quot;width&quot;:130,&quot;height&quot;:100,&quot;type&quot;:&quot;m&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c615129\/u344052\/-3\/s_56d17ef819.jpg&quot;,&quot;width&quot;:100,&quot;height&quot;:75,&quot;type&quot;:&quot;s&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c615129\/u34405 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string docsList {
            get {
                return ResourceManager.GetString("docsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:26,&quot;items&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Биологический&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;Восточный&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;Институт наук о Земле (бывш. Факультет географии и геоэкологии и Геологический факультет)&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Журналистики (Высшая школа журналистики и массовых коммуникаций)&quot;},{&quot;id&quot;:6,&quot;title&quot;:&quot;Институт истории (бывш. Исторический факультет)&quot;}]}}.
        /// </summary>
        internal static string facultiesItemsList {
            get {
                return ResourceManager.GetString("facultiesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:3,&quot;items&quot;:[{&quot;id&quot;:653008904,&quot;from_id&quot;:165146081,&quot;message&quot;:&quot;&quot;,&quot;date&quot;:1458403595,&quot;gift&quot;:{&quot;id&quot;:770,&quot;thumb_256&quot;:&quot;https://vk.com/images/gift/770/256.jpg&quot;,&quot;thumb_96&quot;:&quot;https://vk.com/images/gift/770/96.png&quot;,&quot;thumb_48&quot;:&quot;https://vk.com/images/gift/770/48.png&quot;},&quot;privacy&quot;:1,&quot;gift_hash&quot;:&quot;eOwGaCj1Rc6Itu7T*RdRaIXHIlol27m*cXSHlBbQk0fFvGK4W8yxcKT0c8AcMcYST9FoViFMJoPFY*SOX/t1GLHumPjtYCbbYcwA8lE4WO2sydjoVzs8nKGfZS8*HBNQU6z6CZgxct2qFCCA2iyLDmM4j9jpcbU3MpMwdC1EWcM-&quot;},{&quot;id&quot;:653006597,&quot;from_id&quot;:165146081,&quot;mes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string giftsItemsList {
            get {
                return ResourceManager.GetString("giftsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:3,&quot;items&quot;:[{&quot;id&quot;:65596623,&quot;name&quot;:&quot;FTP&quot;,&quot;screen_name&quot;:&quot;ftp78&quot;,&quot;is_closed&quot;:0,&quot;type&quot;:&quot;page&quot;,&quot;description&quot;:&quot;Чёрный юмор&quot;,&quot;members_count&quot;:341049,&quot;start_date&quot;:19450509,&quot;can_post&quot;:0,&quot;can_see_all_posts&quot;:1,&quot;activity&quot;:&quot;Art and entertainment&quot;,&quot;status&quot;:&quot;иди сюда&quot;,&quot;contacts&quot;:[{&quot;user_id&quot;:171605462,&quot;desc&quot;:&quot;Агент по рекламе &quot;},{&quot;user_id&quot;:313566042,&quot;desc&quot;:&quot;только Реклама . вп не делаем &quot;},{&quot;user_id&quot;:236428820}],&quot;can_upload_doc&quot;:0,&quot;can_upload_video&quot;:0,&quot;can_create_topic&quot;:0,&quot;fixed_post&quot;:1063983,&quot;verified&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string groupsItemsList {
            get {
                return ResourceManager.GetString("groupsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;status&quot;:&quot;not_banned&quot;,&quot;link&quot;:&quot;https://github.com/virtyaluk&quot;}}.
        /// </summary>
        internal static string linkStatus {
            get {
                return ResourceManager.GetString("linkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;type&quot;:&quot;user&quot;,&quot;object_id&quot;: 16815310}}.
        /// </summary>
        internal static string objectInfo {
            get {
                return ResourceManager.GetString("objectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;owner_id&quot;:-26406986,&quot;poll_id&quot;:222496894,&quot;created&quot;:1460316481,&quot;question&quot;:&quot;Насколько ловкие твои руки?&quot;,&quot;votes&quot;:3911,&quot;answer_id&quot;:0,&quot;answers&quot;:[{&quot;id&quot;:739902439,&quot;text&quot;:&quot;Да, умею. Правда на это уходит времени больше, чем на поиски смысла жизни.&quot;,&quot;votes&quot;:401,&quot;rate&quot;:10.250000},{&quot;id&quot;:739902440,&quot;text&quot;:&quot;Легко, по фасту собираю.&quot;,&quot;votes&quot;:233,&quot;rate&quot;:5.960000},{&quot;id&quot;:739902441,&quot;text&quot;:&quot;Собираю ногами, с закрытыми глазами, после 10 кужек пива.&quot;,&quot;votes&quot;:126,&quot;rate&quot;:3.220000},{&quot;id&quot;:739902442,&quot;text&quot;:&quot;Две грани соб [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poll {
            get {
                return ResourceManager.GetString("poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;answer_id&quot;:739946640,&quot;users&quot;:{&quot;count&quot;:1,&quot;items&quot;:[{&quot;id&quot;:16815310,&quot;first_name&quot;:&quot;Богдан&quot;,&quot;last_name&quot;:&quot;Штепан&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;screen_name&quot;:&quot;virtyaluk&quot;}]}},{&quot;answer_id&quot;:739946641,&quot;users&quot;:{&quot;count&quot;:2,&quot;items&quot;:[{&quot;id&quot;:178250508,&quot;first_name&quot;:&quot;Вася&quot;,&quot;last_name&quot;:&quot;Пупкин&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;screen_name&quot;:&quot;make_the_crowd_go&quot;},{&quot;id&quot;:127842370,&quot;first_name&quot;:&quot;Владислав&quot;,&quot;last_name&quot;:&quot;Брин&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;screen_name&quot;:&quot;id127842370&quot;}]}},{&quot;answer_id&quot;:739946642,&quot;users&quot;:{&quot;count&quot;:0,&quot;items&quot;:[]}}]}.
        /// </summary>
        internal static string pollVoters {
            get {
                return ResourceManager.GetString("pollVoters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;first_name&quot;:&quot;Богдан&quot;,&quot;last_name&quot;:&quot;Штепан&quot;,&quot;screen_name&quot;:&quot;virtyaluk&quot;,&quot;sex&quot;:2,&quot;relation&quot;:0,&quot;bdate&quot;:&quot;29.2.0&quot;,&quot;bdate_visibility&quot;:2,&quot;home_town&quot;:&quot;&quot;,&quot;status&quot;:&quot;Together We Are&quot;,&quot;phone&quot;:&quot;+380 **** * ** 52&quot;,&quot;name_request&quot;:{&quot;id&quot;:12345,&quot;status&quot;:&quot;processing&quot;,&quot;first_name&quot;:&quot;Bohdan&quot;,&quot;last_name&quot;:&quot;Shtepan&quot;}}}.
        /// </summary>
        internal static string profileInfo {
            get {
                return ResourceManager.GetString("profileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:6,&quot;items&quot;:[{&quot;id&quot;:16133651,&quot;first_name&quot;:&quot;Vitalik&quot;,&quot;last_name&quot;:&quot;Ulybin&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;domain&quot;:&quot;ylubin&quot;,&quot;screen_name&quot;:&quot;ylubin&quot;,&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10feb\/bemQ80NlFWM.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fea\/5xmjTRE-1Bg.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe9\/BInBMF-GmS8.jpg&quot;,&quot;photo_200_orig&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe7\/sHgM2UkEh2o.jpg&quot;,&quot;has_mobile&quot;:1,&quot;wall_comments&quot;:0,&quot;can_post [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string profilesMixedList {
            get {
                return ResourceManager.GetString("profilesMixedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:83,&quot;items&quot;:[{&quot;id&quot;:1000001,&quot;title&quot;:&quot;Адыгея&quot;},{&quot;id&quot;:1121540,&quot;title&quot;:&quot;Алтай&quot;},{&quot;id&quot;:1121829,&quot;title&quot;:&quot;Алтайский край&quot;},{&quot;id&quot;:1123488,&quot;title&quot;:&quot;Амурская область&quot;},{&quot;id&quot;:1000236,&quot;title&quot;:&quot;Архангельская область&quot;}]}}.
        /// </summary>
        internal static string regionsItemsList {
            get {
                return ResourceManager.GetString("regionsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:0}.
        /// </summary>
        internal static string responseFalse {
            get {
                return ResourceManager.GetString("responseFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:481516}.
        /// </summary>
        internal static string responseNum {
            get {
                return ResourceManager.GetString("responseNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[12345,-54321,1,-2]}.
        /// </summary>
        internal static string responseNumsList {
            get {
                return ResourceManager.GetString("responseNumsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:1}.
        /// </summary>
        internal static string responseTrue {
            get {
                return ResourceManager.GetString("responseTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:3211,&quot;items&quot;:[{&quot;id&quot;:8243,&quot;title&quot;:&quot;Anglo-American School of Moscow&quot;},{&quot;id&quot;:5780,&quot;title&quot;:&quot;Anglo-Russian School 497&quot;},{&quot;id&quot;:1669882,&quot;title&quot;:&quot;English International School Moscow&quot;},{&quot;id&quot;:1687981,&quot;title&quot;:&quot;Авиационная школа «Гамаюн»&quot;},{&quot;id&quot;:1706632,&quot;title&quot;:&quot;Авиационная школа Аэрофлота&quot;}]}}.
        /// </summary>
        internal static string schoolsItemsList {
            get {
                return ResourceManager.GetString("schoolsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:1460247613}.
        /// </summary>
        internal static string serverTime {
            get {
                return ResourceManager.GetString("serverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;changed&quot;:1,&quot;name_request&quot;:{&quot;id&quot;:12345,&quot;status&quot;:&quot;processing&quot;,&quot;first_name&quot;:&quot;Bohdan&quot;,&quot;last_name&quot;:&quot;Shtepan&quot;}}}.
        /// </summary>
        internal static string setProfileInfo {
            get {
                return ResourceManager.GetString("setProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;key&quot;:&quot;foo&quot;,&quot;value&quot;:&quot;bar&quot;}]}.
        /// </summary>
        internal static string storageValsList {
            get {
                return ResourceManager.GetString("storageValsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;8 Марта ул.&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;А\/Д Подъезд к а. Гатлукай дор.&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;А\/Д Подъезд к г. Адыгейску дор.&quot;},{&quot;id&quot;:4,&quot;title&quot;:&quot;А\/Д Подъезд к ж\/д станции Псекупс дор.&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;А\/Д Пчегатлукай-Гатлукай-Адыгейск дор.&quot;}]}.
        /// </summary>
        internal static string streetsList {
            get {
                return ResourceManager.GetString("streetsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[&quot;foo&quot;,&quot;bar&quot;,&quot;baz&quot;]}.
        /// </summary>
        internal static string stringsList {
            get {
                return ResourceManager.GetString("stringsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:80,&quot;items&quot;:[{&quot;id&quot;:21972158,&quot;title&quot;:&quot;Вопросы по поводу создания приложений&quot;,&quot;created&quot;:1260720340,&quot;created_by&quot;:189814,&quot;updated&quot;:1460560838,&quot;updated_by&quot;:239489016,&quot;is_closed&quot;:0,&quot;is_fixed&quot;:1,&quot;comments&quot;:20490},{&quot;id&quot;:21972169,&quot;title&quot;:&quot;Замеченные ошибки в API или документации&quot;,&quot;created&quot;:1260720510,&quot;created_by&quot;:189814,&quot;updated&quot;:1363956097,&quot;updated_by&quot;:189814,&quot;is_closed&quot;:1,&quot;is_fixed&quot;:1,&quot;comments&quot;:3747},{&quot;id&quot;:27042222,&quot;title&quot;:&quot;Обновлённый платежный API для приложений&quot;,&quot;created&quot;:1348220340,&quot;create [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string topicItemsList {
            get {
                return ResourceManager.GetString("topicItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:7,&quot;items&quot;:[{&quot;id&quot;:1,&quot;name&quot;:&quot;Текстовые&quot;,&quot;count&quot;:21},{&quot;id&quot;:2,&quot;name&quot;:&quot;Архивы&quot;,&quot;count&quot;:10},{&quot;id&quot;:3,&quot;name&quot;:&quot;Анимации&quot;,&quot;count&quot;:257},{&quot;id&quot;:4,&quot;name&quot;:&quot;Изображения&quot;,&quot;count&quot;:26},{&quot;id&quot;:5,&quot;name&quot;:&quot;Музыка&quot;,&quot;count&quot;:1},{&quot;id&quot;:6,&quot;name&quot;:&quot;Видео&quot;,&quot;count&quot;:1},{&quot;id&quot;:8,&quot;name&quot;:&quot;Прочие&quot;,&quot;count&quot;:459}]}}.
        /// </summary>
        internal static string typesItemsList {
            get {
                return ResourceManager.GetString("typesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:702,&quot;items&quot;:[{&quot;id&quot;:2,&quot;title&quot;:&quot;МГУ&quot;},{&quot;id&quot;:86,&quot;title&quot;:&quot;АПИ при ИГиП РАН&quot;},{&quot;id&quot;:87,&quot;title&quot;:&quot;Финансовый университет (бывш. ГУМФ)&quot;},{&quot;id&quot;:88,&quot;title&quot;:&quot;АГПС МЧС России&quot;},{&quot;id&quot;:89,&quot;title&quot;:&quot;АГЗ МЧС России&quot;}]}}.
        /// </summary>
        internal static string universitiesItemsList {
            get {
                return ResourceManager.GetString("universitiesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;upload_url&quot;:&quot;some_upload_url&quot;}}.
        /// </summary>
        internal static string uploadServer {
            get {
                return ResourceManager.GetString("uploadServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:3,&quot;items&quot;:[{&quot;id&quot;:16133651,&quot;first_name&quot;:&quot;Vitalik&quot;,&quot;last_name&quot;:&quot;Ulybin&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;domain&quot;:&quot;ylubin&quot;,&quot;screen_name&quot;:&quot;ylubin&quot;,&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10feb\/bemQ80NlFWM.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fea\/5xmjTRE-1Bg.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe9\/BInBMF-GmS8.jpg&quot;,&quot;photo_200_orig&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe7\/sHgM2UkEh2o.jpg&quot;,&quot;has_mobile&quot;:1,&quot;wall_comments&quot;:0,&quot;can_post [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usersItemsList {
            get {
                return ResourceManager.GetString("usersItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:16133651,&quot;first_name&quot;:&quot;Vitalik&quot;,&quot;last_name&quot;:&quot;Ulybin&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;domain&quot;:&quot;ylubin&quot;,&quot;screen_name&quot;:&quot;ylubin&quot;,&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10feb\/bemQ80NlFWM.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fea\/5xmjTRE-1Bg.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe9\/BInBMF-GmS8.jpg&quot;,&quot;photo_200_orig&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe7\/sHgM2UkEh2o.jpg&quot;,&quot;has_mobile&quot;:1,&quot;wall_comments&quot;:0,&quot;can_post&quot;:0,&quot;can_see_all_po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usersList {
            get {
                return ResourceManager.GetString("usersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;text&quot;:&quot;Major Lazer x Showtek – I’m a Believer&quot;,&quot;audio&quot;:{&quot;id&quot;:456239425,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Major Lazer x Showtek&quot;,&quot;title&quot;:&quot;I’m a Believer&quot;,&quot;duration&quot;:254,&quot;date&quot;:1460392491,&quot;url&quot;:&quot;https : //cs7-5v4.v...c7EHzS9BZw1y1TWZ48c&quot;,&quot;genre_id&quot;:18,&quot;no_search&quot;:1}}}.
        /// </summary>
        internal static string userStatus {
            get {
                return ResourceManager.GetString("userStatus", resourceCulture);
            }
        }
    }
}
