//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernDev.InTouch.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockJsonResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockJsonResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernDev.InTouch.Tests.MockJsonResponses", typeof(MockJsonResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;found&quot;:[{&quot;id&quot;:16133651,&quot;first_name&quot;:&quot;Vitalik&quot;,&quot;last_name&quot;:&quot;Ulybin&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;domain&quot;:&quot;ylubin&quot;,&quot;screen_name&quot;:&quot;ylubin&quot;,&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10feb\/bemQ80NlFWM.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fea\/5xmjTRE-1Bg.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe9\/BInBMF-GmS8.jpg&quot;,&quot;photo_200_orig&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe7\/sHgM2UkEh2o.jpg&quot;,&quot;has_mobile&quot;:1,&quot;wall_comments&quot;:0,&quot;can_post&quot;:0,&quot;can_s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string accountContacts {
            get {
                return ResourceManager.GetString("accountContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;friends&quot;:733,&quot;messages&quot;:21,&quot;gifts&quot;:2,&quot;app_requests&quot;:1}}.
        /// </summary>
        internal static string accountCounters {
            get {
                return ResourceManager.GetString("accountCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;country&quot;:&quot;UA&quot;,&quot;https_required&quot;:1,&quot;own_posts_default&quot;:1,&quot;no_wall_replies&quot;:1,&quot;intro&quot;:0,&quot;lang&quot;:0}}.
        /// </summary>
        internal static string accountInfo {
            get {
                return ResourceManager.GetString("accountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;comment_id&quot;:8227}}.
        /// </summary>
        internal static string addComment {
            get {
                return ResourceManager.GetString("addComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;list_id&quot;:2}}.
        /// </summary>
        internal static string addFriendsList {
            get {
                return ResourceManager.GetString("addFriendsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;market_album_id&quot;:481516}}.
        /// </summary>
        internal static string addMarketAlbum {
            get {
                return ResourceManager.GetString("addMarketAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;error&quot;:{&quot;error_code&quot;:14,&quot;error_msg&quot;:&quot;Captcha needed&quot;,&quot;request_params&quot;:[{&quot;key&quot;:&quot;oauth&quot;,&quot;value&quot;:&quot;1&quot;},{&quot;key&quot;:&quot;foo&quot;,&quot;value&quot;:&quot;bar&quot;},{&quot;key&quot;:&quot;method&quot;,&quot;value&quot;:&quot;users.getFollowers&quot;}],&quot;captcha_sid&quot;:&quot;239633676097&quot;,&quot;captcha_img&quot;:&quot;http:\/\/api.vk.com\/captcha.php?sid=239633676097&amp;s=1&quot;}}.
        /// </summary>
        internal static string apiError14 {
            get {
                return ResourceManager.GetString("apiError14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;error&quot;:{&quot;error_code&quot;:5,&quot;error_msg&quot;:&quot;User authorization failed: access_token was given to another ip address.&quot;,&quot;request_params&quot;:[{&quot;key&quot;:&quot;oauth&quot;,&quot;value&quot;:&quot;1&quot;},{&quot;key&quot;:&quot;foo&quot;,&quot;value&quot;:&quot;bar&quot;}]}}.
        /// </summary>
        internal static string apiError5 {
            get {
                return ResourceManager.GetString("apiError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;user_id&quot;:66748,&quot;friend_status&quot;:0,&quot;sign&quot;:&quot;cd56c1006d87caf27377459caf3c4a03&quot;},{&quot;user_id&quot;:123161616,&quot;friend_status&quot;:2,&quot;sign&quot;:&quot;c696e40846194051174887e3341bc369&quot;}]}.
        /// </summary>
        internal static string areFriends {
            get {
                return ResourceManager.GetString("areFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;items&quot;:[{&quot;type&quot;:&quot;photo&quot;,&quot;photo&quot;:{&quot;id&quot;:410545563,&quot;album_id&quot;:-12,&quot;owner_id&quot;:-1,&quot;user_id&quot;:100,&quot;photo_75&quot;:&quot;https://pp.vk.me/...9bb/cC1ndaaUcag.jpg&quot;,&quot;photo_130&quot;:&quot;https://pp.vk.me/...9bc/4OoKxEUaaaE.jpg&quot;,&quot;photo_604&quot;:&quot;https://pp.vk.me/...9bd/Vz1oR972bIU.jpg&quot;,&quot;photo_807&quot;:&quot;https://pp.vk.me/...9be/Xpal8cOqSh8.jpg&quot;,&quot;photo_1280&quot;:&quot;https://pp.vk.me/...9bf/MBBQvMzlGSk.jpg&quot;,&quot;width&quot;:682,&quot;height&quot;:910,&quot;text&quot;:&quot;&quot;,&quot;date&quot;:1459494929,&quot;access_key&quot;:&quot;8f8a322694516efaf2&quot;}},{&quot;type&quot;:&quot;video&quot;,&quot;video&quot;:{&quot;id&quot;:172047301,&quot;owner_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string attachmentsItemsList {
            get {
                return ResourceManager.GetString("attachmentsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;id&quot;:456239447,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Ghastly&quot;,&quot;title&quot;:&quot;Get On This (Ghastly x Ablaze VIP)&quot;,&quot;duration&quot;:249,&quot;date&quot;:1460490199,&quot;url&quot;:&quot;https://cs7-4v4.v...WnpkZxdJH-KkPfxRvmQ&quot;}}.
        /// </summary>
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:15,&quot;items&quot;:[{&quot;id&quot;:71581179,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;Future House&quot;},{&quot;id&quot;:48731778,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;Laidback Luke&apos; Mixsmash Radio&quot;},{&quot;id&quot;:48731762,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;W&amp;amp;W&apos; Mainstage&quot;}]}}.
        /// </summary>
        internal static string audioAlbumItemsList {
            get {
                return ResourceManager.GetString("audioAlbumItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:6000,&quot;items&quot;:[{&quot;id&quot;:456239447,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Ghastly&quot;,&quot;title&quot;:&quot;Get On This (Ghastly x Ablaze VIP)&quot;,&quot;duration&quot;:249,&quot;date&quot;:1460490199,&quot;url&quot;:&quot;https://cs7-4v4.v...WnpkZxdJH-KkPfxRvmQ&quot;},{&quot;id&quot;:456239446,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Ghastly &amp; Mija&quot;,&quot;title&quot;:&quot;Crank It (feat. Lil Jon) vk.com/itunesmusic_inc&quot;,&quot;duration&quot;:255,&quot;date&quot;:1460463175,&quot;url&quot;:&quot;https://psv4.vk.m...zrOW_RuTa6p6a_IjH7Q&quot;,&quot;genre_id&quot;:2},{&quot;id&quot;:456239445,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Eptic &amp; Habstrakt&quot;,&quot;title&quot;:&quot;On The [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string audioItemsList {
            get {
                return ResourceManager.GetString("audioItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:456239447,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Ghastly&quot;,&quot;title&quot;:&quot;Get On This (Ghastly x Ablaze VIP)&quot;,&quot;duration&quot;:249,&quot;date&quot;:1460490199,&quot;url&quot;:&quot;https://cs7-4v4.v...WnpkZxdJH-KkPfxRvmQ&quot;},{&quot;id&quot;:456239446,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Ghastly &amp; Mija&quot;,&quot;title&quot;:&quot;Crank It (feat. Lil Jon) vk.com/itunesmusic_inc&quot;,&quot;duration&quot;:255,&quot;date&quot;:1460463175,&quot;url&quot;:&quot;https://psv4.vk.m...zrOW_RuTa6p6a_IjH7Q&quot;,&quot;genre_id&quot;:2},{&quot;id&quot;:456239445,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Eptic &amp; Habstrakt&quot;,&quot;title&quot;:&quot;On The Block (Blvk Sheep x S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string audioList {
            get {
                return ResourceManager.GetString("audioList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;lyrics_id&quot;:2428970,&quot;text&quot;:&quot;I&apos;ve got a mission A magic to perform, This rite of passage, Like the riders of the storm.&quot;}}.
        /// </summary>
        internal static string audioLyrics {
            get {
                return ResourceManager.GetString("audioLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;sid&quot;:&quot;super_sid&quot;,&quot;success&quot;:1,&quot;uid&quot;:12345}}.
        /// </summary>
        internal static string authStatus {
            get {
                return ResourceManager.GetString("authStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:65596623,&quot;name&quot;:&quot;FTP&quot;,&quot;screen_name&quot;:&quot;ftp78&quot;,&quot;is_closed&quot;:0,&quot;type&quot;:&quot;page&quot;,&quot;description&quot;:&quot;Чёрный юмор&quot;,&quot;members_count&quot;:341049,&quot;start_date&quot;:19450509,&quot;can_post&quot;:0,&quot;can_see_all_posts&quot;:1,&quot;activity&quot;:&quot;Art and entertainment&quot;,&quot;status&quot;:&quot;иди сюда&quot;,&quot;contacts&quot;:[{&quot;user_id&quot;:171605462,&quot;desc&quot;:&quot;Агент по рекламе &quot;},{&quot;user_id&quot;:313566042,&quot;desc&quot;:&quot;только Реклама . вп не делаем &quot;},{&quot;user_id&quot;:236428820}],&quot;can_upload_doc&quot;:0,&quot;can_upload_video&quot;:0,&quot;can_create_topic&quot;:0,&quot;fixed_post&quot;:1063983,&quot;verified&quot;:0,&quot;site&quot;:&quot;&quot;,&quot;main_a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string broadcastList {
            get {
                return ResourceManager.GetString("broadcastList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:18,&quot;items&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Агрохимии&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;Биофизики&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;Биохимии&quot;},{&quot;id&quot;:4,&quot;title&quot;:&quot;Ботаники&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Генетики и биотехнологии&quot;}]}}.
        /// </summary>
        internal static string chairsItemsList {
            get {
                return ResourceManager.GetString("chairsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;token&quot;:&quot;super_token&quot;,&quot;secret&quot;:&quot;super_secret&quot;}}.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;id&quot;:1,&quot;type&quot;:&quot;chat&quot;,&quot;title&quot;:&quot;олололо ок,да??&quot;,&quot;admin_id&quot;:16815310,&quot;users&quot;:[{&quot;id&quot;:16815310,&quot;first_name&quot;:&quot;Богдана&quot;,&quot;last_name&quot;:&quot;Штепана&quot;,&quot;sex&quot;:2,&quot;invited_by&quot;:16815310,&quot;type&quot;:&quot;profile&quot;}]}}.
        /// </summary>
        internal static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:96,&quot;items&quot;:[{&quot;id&quot;:&quot;3796764_1127&quot;,&quot;user_id&quot;:3796764,&quot;post_id&quot;:1127,&quot;date&quot;:1461004126,&quot;latitude&quot;:0.000000,&quot;longitude&quot;:0.000000,&quot;text&quot;:&quot;#СловомиМузыкой Творческий вечер Андрея Пастушенко &lt;br&gt;#АнтонАвдеев #ВячеславШтыпс #ИлияДьяков #АндрейПастушенко #ДарьяКотюх #МананаГогитидзе #КириллГордеев #ВераСвешникова #РостиславКолпаков @ Концертный зал у Финляндского&quot;,&quot;place_id&quot;:0,&quot;place_title&quot;:&quot;&quot;,&quot;place_country&quot;:0,&quot;place_city&quot;:0,&quot;place_address&quot;:&quot;&quot;,&quot;place_type&quot;:0,&quot;place_icon&quot;:&quot;http:\/\/vk.com\/image [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string checkinsItemsList {
            get {
                return ResourceManager.GetString("checkinsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:18,&quot;items&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Москва&quot;,&quot;important&quot;:1},{&quot;id&quot;:2,&quot;title&quot;:&quot;Санкт-Петербург&quot;,&quot;important&quot;:1},{&quot;id&quot;:10,&quot;title&quot;:&quot;Волгоград&quot;},{&quot;id&quot;:37,&quot;title&quot;:&quot;Владивосток&quot;},{&quot;id&quot;:153,&quot;title&quot;:&quot;Хабаровск&quot;}]}}.
        /// </summary>
        internal static string citiesItemsList {
            get {
                return ResourceManager.GetString("citiesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Москва&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;Санкт-Петербург&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;&quot;},{&quot;id&quot;:4,&quot;title&quot;:&quot;Herzliya&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Отрадное&quot;}]}.
        /// </summary>
        internal static string citiesList {
            get {
                return ResourceManager.GetString("citiesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot; : {
        ///		&quot;count&quot; : 20490,
        ///		&quot;items&quot; : [{
        ///				&quot;id&quot; : 85995,
        ///				&quot;from_id&quot; : 7219163,
        ///				&quot;date&quot; : 1459494929,
        ///				&quot;text&quot; : &quot;Здравствуйте.&quot;,
        ///				&quot;likes&quot; : {
        ///					&quot;count&quot; : 0,
        ///					&quot;user_likes&quot; : 0,
        ///					&quot;can_like&quot; : 1
        ///				},
        ///				&quot;attachments&quot; : [{
        ///						&quot;type&quot; : &quot;photo&quot;,
        ///						&quot;photo&quot; : {
        ///							&quot;id&quot; : 410545563,
        ///							&quot;album_id&quot; : -12,
        ///							&quot;owner_id&quot; : -1,
        ///							&quot;user_id&quot; : 100,
        ///							&quot;photo_75&quot; : &quot;https://pp.vk.me/...9bb/cC1ndaaUcag.jpg&quot;,
        ///							&quot;photo_130&quot; : &quot;https://p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commentItemsList {
            get {
                return ResourceManager.GetString("commentItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:234,&quot;items&quot;:[{&quot;id&quot;:19,&quot;title&quot;:&quot;Австралия&quot;},{&quot;id&quot;:20,&quot;title&quot;:&quot;Австрия&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Азербайджан&quot;},{&quot;id&quot;:21,&quot;title&quot;:&quot;Албания&quot;},{&quot;id&quot;:22,&quot;title&quot;:&quot;Алжир&quot;}]}}.
        /// </summary>
        internal static string countriesItemsList {
            get {
                return ResourceManager.GetString("countriesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Россия&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;Украина&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;Беларусь&quot;},{&quot;id&quot;:4,&quot;title&quot;:&quot;Казахстан&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Азербайджан&quot;}]}.
        /// </summary>
        internal static string countriesList {
            get {
                return ResourceManager.GetString("countriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:463,&quot;unread_dialogs&quot;:22,&quot;items&quot;:[{&quot;message&quot;:{&quot;id&quot;:147673,&quot;date&quot;:1461274931,&quot;out&quot;:1,&quot;user_id&quot;:127842370,&quot;read_state&quot;:0,&quot;title&quot;:&quot; ... &quot;,&quot;body&quot;:&quot;text&quot;,&quot;random_id&quot;:0,&quot;attachments&quot;:[{&quot;type&quot;:&quot;photo&quot;,&quot;photo&quot;:{&quot;id&quot;:410545563,&quot;album_id&quot;:-12,&quot;owner_id&quot;:-1,&quot;user_id&quot;:100,&quot;photo_75&quot;:&quot;https://pp.vk.me/...9bb/cC1ndaaUcag.jpg&quot;,&quot;photo_130&quot;:&quot;https://pp.vk.me/...9bc/4OoKxEUaaaE.jpg&quot;,&quot;photo_604&quot;:&quot;https://pp.vk.me/...9bd/Vz1oR972bIU.jpg&quot;,&quot;photo_807&quot;:&quot;https://pp.vk.me/...9be/Xpal8cOqSh8.jpg&quot;,&quot;photo_1280&quot;:&quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dialogsItemsList {
            get {
                return ResourceManager.GetString("dialogsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:775,&quot;items&quot;:[{&quot;id&quot;:437429925,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;file.gif&quot;,&quot;size&quot;:428000,&quot;ext&quot;:&quot;gif&quot;,&quot;url&quot;:&quot;https:\/\/vk.com\/doc16815310_437429925?hash=1fb22b7ab82e2eb4f1&amp;dl=1460677884646710e77e68f9dffa&amp;api=1&quot;,&quot;date&quot;:1460580469,&quot;type&quot;:3,&quot;preview&quot;:{&quot;photo&quot;:{&quot;sizes&quot;:[{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c615129\/u344052\/-3\/m_56d17ef819.jpg&quot;,&quot;width&quot;:130,&quot;height&quot;:100,&quot;type&quot;:&quot;m&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c615129\/u344052\/-3\/s_56d17ef819.jpg&quot;,&quot;width&quot;:100,&quot;height&quot;:75,&quot;type&quot;:&quot;s&quot;},{&quot;src&quot;:&quot;https:\/\/pp.v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string docsItemsList {
            get {
                return ResourceManager.GetString("docsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:437429925,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;file.gif&quot;,&quot;size&quot;:428000,&quot;ext&quot;:&quot;gif&quot;,&quot;url&quot;:&quot;https:\/\/vk.com\/doc16815310_437429925?hash=1fb22b7ab82e2eb4f1&amp;dl=1460677884646710e77e68f9dffa&amp;api=1&quot;,&quot;date&quot;:1460580469,&quot;type&quot;:3,&quot;preview&quot;:{&quot;photo&quot;:{&quot;sizes&quot;:[{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c615129\/u344052\/-3\/m_56d17ef819.jpg&quot;,&quot;width&quot;:130,&quot;height&quot;:100,&quot;type&quot;:&quot;m&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c615129\/u344052\/-3\/s_56d17ef819.jpg&quot;,&quot;width&quot;:100,&quot;height&quot;:75,&quot;type&quot;:&quot;s&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c615129\/u34405 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string docsList {
            get {
                return ResourceManager.GetString("docsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;base_url&quot;: &quot;https://vk.com/images/stickers&quot;,&quot;sticker_ids&quot;: [3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3211, 3212, 3213, 3214, 3215, 3216, 3217, 3218, 3219, 3220, 3221, 3222, 3223, 3224, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3239, 3240, 3241, 3242, 3243, 3244]}}.
        /// </summary>
        internal static string editorStickers {
            get {
                return ResourceManager.GetString("editorStickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{success:1,address:&quot;place_address&quot;}}.
        /// </summary>
        internal static string editPlace {
            get {
                return ResourceManager.GetString("editPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:26,&quot;items&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Биологический&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;Восточный&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;Институт наук о Земле (бывш. Факультет географии и геоэкологии и Геологический факультет)&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Журналистики (Высшая школа журналистики и массовых коммуникаций)&quot;},{&quot;id&quot;:6,&quot;title&quot;:&quot;Институт истории (бывш. Исторический факультет)&quot;}]}}.
        /// </summary>
        internal static string facultiesItemsList {
            get {
                return ResourceManager.GetString("facultiesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;success&quot;:1,&quot;friend_deleted&quot;:1}}.
        /// </summary>
        internal static string friendDeleteStatus {
            get {
                return ResourceManager.GetString("friendDeleteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:2,&quot;items&quot;:[{&quot;name&quot;:&apos;:-*&apos;,&quot;id&quot;:1},{&quot;name&quot;:&apos;^_^&apos;,&quot;id&quot;:2}]}}.
        /// </summary>
        internal static string friendsLists {
            get {
                return ResourceManager.GetString("friendsLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;code&quot;:&quot;confirmationCode&quot;}}.
        /// </summary>
        internal static string getCallbackConfirmationCode {
            get {
                return ResourceManager.GetString("getCallbackConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;secret_key&quot;:&quot;secretKey&quot;,&quot;server_url&quot;:&quot;serverUrl&quot;}}.
        /// </summary>
        internal static string getCallbackServerSettings {
            get {
                return ResourceManager.GetString("getCallbackServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;message_new&quot;:true,&quot;wall_reply_new&quot;:false}}.
        /// </summary>
        internal static string getCallbackSettings {
            get {
                return ResourceManager.GetString("getCallbackSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:3,&quot;items&quot;:[{&quot;id&quot;:653008904,&quot;from_id&quot;:165146081,&quot;message&quot;:&quot;&quot;,&quot;date&quot;:1458403595,&quot;gift&quot;:{&quot;id&quot;:770,&quot;thumb_256&quot;:&quot;https://vk.com/images/gift/770/256.jpg&quot;,&quot;thumb_96&quot;:&quot;https://vk.com/images/gift/770/96.png&quot;,&quot;thumb_48&quot;:&quot;https://vk.com/images/gift/770/48.png&quot;},&quot;privacy&quot;:1,&quot;gift_hash&quot;:&quot;eOwGaCj1Rc6Itu7T*RdRaIXHIlol27m*cXSHlBbQk0fFvGK4W8yxcKT0c8AcMcYST9FoViFMJoPFY*SOX/t1GLHumPjtYCbbYcwA8lE4WO2sydjoVzs8nKGfZS8*HBNQU6z6CZgxct2qFCCA2iyLDmM4j9jpcbU3MpMwdC1EWcM-&quot;},{&quot;id&quot;:653006597,&quot;from_id&quot;:165146081,&quot;mes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string giftsItemsList {
            get {
                return ResourceManager.GetString("giftsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;id&quot;:65596623,&quot;name&quot;:&quot;FTP&quot;,&quot;screen_name&quot;:&quot;ftp78&quot;,&quot;is_closed&quot;:0,&quot;type&quot;:&quot;page&quot;,&quot;description&quot;:&quot;Чёрный юмор&quot;,&quot;members_count&quot;:341049,&quot;start_date&quot;:19450509,&quot;can_post&quot;:0,&quot;can_see_all_posts&quot;:1,&quot;activity&quot;:&quot;Art and entertainment&quot;,&quot;status&quot;:&quot;иди сюда&quot;,&quot;contacts&quot;:[{&quot;user_id&quot;:171605462,&quot;desc&quot;:&quot;Агент по рекламе &quot;},{&quot;user_id&quot;:313566042,&quot;desc&quot;:&quot;только Реклама . вп не делаем &quot;},{&quot;user_id&quot;:236428820}],&quot;can_upload_doc&quot;:0,&quot;can_upload_video&quot;:0,&quot;can_create_topic&quot;:0,&quot;fixed_post&quot;:1063983,&quot;verified&quot;:0,&quot;site&quot;:&quot;&quot;,&quot;main_al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;id&quot;:124,&quot;url&quot;:&quot;link_url&quot;,&quot;name&quot;:&quot;link name&quot;,&quot;edit_title&quot;:1,&quot;desc&quot;:&quot;link description&quot;,&quot;image_processing&quot;:1}}.
        /// </summary>
        internal static string groupAddLink {
            get {
                return ResourceManager.GetString("groupAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;member&quot;:0,&quot;request&quot;:1}}.
        /// </summary>
        internal static string groupIsMember {
            get {
                return ResourceManager.GetString("groupIsMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;enabled&quot;:1,&quot;categories&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;Рекомендации&quot;,&quot;page_count&quot;:16,&quot;page_previews&quot;:[{&quot;id&quot;:59576823,&quot;name&quot;:&quot;ONUKA&quot;,&quot;screen_name&quot;:&quot;onuka&quot;,&quot;is_closed&quot;:0,&quot;type&quot;:&quot;group&quot;,&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c633718\/v633718415\/1b94a\/HuF1djxpQgA.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c633718\/v633718415\/1b949\/DgRtxTs0xg0.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c633718\/v633718415\/1b948\/boTmiSBZo6U.jpg&quot;}]},{&quot;id&quot;:1,&quot;name&quot;:&quot;Новости&quot;,&quot;page_count&quot;:11,&quot;page_previews&quot;:[{&quot;id&quot;:44721377,&quot;name&quot;:&quot;События&quot;,&quot;sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string groupsCatalogInfo {
            get {
                return ResourceManager.GetString("groupsCatalogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;title&quot;:&quot;Group title&quot;,&quot;description&quot;:&quot;Group description&quot;,&quot;address&quot;:&quot;alex_boroda4&quot;,&quot;country_id&quot;:0,&quot;city_id&quot;:0,&quot;wall&quot;:1,&quot;photos&quot;:1,&quot;video&quot;:1,&quot;audio&quot;:1,&quot;docs&quot;:0,&quot;topics&quot;:1,&quot;wiki&quot;:0,&quot;public_date&quot;:&quot;1.1.2009&quot;,&quot;public_date_label&quot;:&quot;Дата рождения:&quot;,&quot;public_category&quot;:&quot;328&quot;,&quot;public_subcategory&quot;:&quot;0&quot;,&quot;public_category_list&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;Не выбрана&quot;},{&quot;id&quot;:301,&quot;name&quot;:&quot;Ведущий \/ Ведущая&quot;},{&quot;id&quot;:302,&quot;name&quot;:&quot;Госслужащий \/ Госслужащая&quot;},{&quot;id&quot;:303,&quot;name&quot;:&quot;Духовное лицо&quot;},{&quot;id&quot;:304,&quot;name&quot;:&quot;Журналист&quot;},{&quot;id&quot;:30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string groupSettings {
            get {
                return ResourceManager.GetString("groupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:3,&quot;items&quot;:[{&quot;id&quot;:65596623,&quot;name&quot;:&quot;FTP&quot;,&quot;screen_name&quot;:&quot;ftp78&quot;,&quot;is_closed&quot;:0,&quot;type&quot;:&quot;page&quot;,&quot;description&quot;:&quot;Чёрный юмор&quot;,&quot;members_count&quot;:341049,&quot;start_date&quot;:19450509,&quot;can_post&quot;:0,&quot;can_see_all_posts&quot;:1,&quot;activity&quot;:&quot;Art and entertainment&quot;,&quot;status&quot;:&quot;иди сюда&quot;,&quot;contacts&quot;:[{&quot;user_id&quot;:171605462,&quot;desc&quot;:&quot;Агент по рекламе &quot;},{&quot;user_id&quot;:313566042,&quot;desc&quot;:&quot;только Реклама . вп не делаем &quot;},{&quot;user_id&quot;:236428820}],&quot;can_upload_doc&quot;:0,&quot;can_upload_video&quot;:0,&quot;can_create_topic&quot;:0,&quot;fixed_post&quot;:1063983,&quot;verified&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string groupsItemsList {
            get {
                return ResourceManager.GetString("groupsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:65596623,&quot;name&quot;:&quot;FTP&quot;,&quot;screen_name&quot;:&quot;ftp78&quot;,&quot;is_closed&quot;:0,&quot;type&quot;:&quot;page&quot;,&quot;description&quot;:&quot;Чёрный юмор&quot;,&quot;members_count&quot;:341049,&quot;start_date&quot;:19450509,&quot;can_post&quot;:0,&quot;can_see_all_posts&quot;:1,&quot;activity&quot;:&quot;Art and entertainment&quot;,&quot;status&quot;:&quot;иди сюда&quot;,&quot;contacts&quot;:[{&quot;user_id&quot;:171605462,&quot;desc&quot;:&quot;Агент по рекламе &quot;},{&quot;user_id&quot;:313566042,&quot;desc&quot;:&quot;только Реклама . вп не делаем &quot;},{&quot;user_id&quot;:236428820}],&quot;can_upload_doc&quot;:0,&quot;can_upload_video&quot;:0,&quot;can_create_topic&quot;:0,&quot;fixed_post&quot;:1063983,&quot;verified&quot;:0,&quot;site&quot;:&quot;&quot;,&quot;main_a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string groupsList {
            get {
                return ResourceManager.GetString("groupsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;liked&quot;:1,&quot;copied&quot;:1}}.
        /// </summary>
        internal static string isLiked {
            get {
                return ResourceManager.GetString("isLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;likes&quot;:123}}.
        /// </summary>
        internal static string likesCount {
            get {
                return ResourceManager.GetString("likesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:23,&quot;items&quot;:[{&quot;id&quot;:&quot;2_16815310_98093993&quot;,&quot;url&quot;:&quot;https:\/\/vk.com\/snapster&quot;,&quot;title&quot;:&quot;Snapster&quot;,&quot;description&quot;:&quot;Сообщество&quot;,&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c627324\/v627324034\/3f305\/fg9-C9etAK0.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c627324\/v627324034\/3f304\/_lRrz_JHd1c.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c627324\/v627324034\/3f302\/ikuRdAQysIo.jpg&quot;},{&quot;id&quot;:&quot;2_16815310_104669514&quot;,&quot;url&quot;:&quot;https:\/\/vk.com\/vkmc&quot;,&quot;title&quot;:&quot;VK Mobile Challenge&quot;,&quot;description&quot;:&quot;Сообщество&quot;,&quot;photo_50&quot;:&quot;https:\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string linksItemsList {
            get {
                return ResourceManager.GetString("linksItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;status&quot;:&quot;not_banned&quot;,&quot;link&quot;:&quot;https://github.com/virtyaluk&quot;}}.
        /// </summary>
        internal static string linkStatus {
            get {
                return ResourceManager.GetString("linkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:9,&quot;items&quot;:[{&quot;id&quot;:1,&quot;owner_id&quot;:-43195721,&quot;title&quot;:&quot;Верхняя одежда&quot;,&quot;count&quot;:37,&quot;updated_time&quot;:1442081607,&quot;photo&quot;:{&quot;id&quot;:379131663,&quot;album_id&quot;:-53,&quot;owner_id&quot;:-43195721,&quot;user_id&quot;:100,&quot;photo_75&quot;:&quot;https:\/\/pp.vk.me\/c628418\/v628418464\/13ed3\/omjTSK0_zdE.jpg&quot;,&quot;photo_130&quot;:&quot;https:\/\/pp.vk.me\/c628418\/v628418464\/13ed4\/pXwt5PGb1xk.jpg&quot;,&quot;photo_604&quot;:&quot;https:\/\/pp.vk.me\/c628418\/v628418464\/13ed5\/gDPBCpdWVnQ.jpg&quot;,&quot;photo_807&quot;:&quot;https:\/\/pp.vk.me\/c628418\/v628418464\/13ed6\/yxm0IQc8Seo.jpg&quot;,&quot;wid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string marketAlbumsItemsList {
            get {
                return ResourceManager.GetString("marketAlbumsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:85,&quot;items&quot;:[{&quot;id&quot;:1,&quot;name&quot;:&quot;Женская одежда&quot;,&quot;section&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;Гардероб&quot;}},{&quot;id&quot;:2,&quot;name&quot;:&quot;Мужская одежда&quot;,&quot;section&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;Гардероб&quot;}},{&quot;id&quot;:3,&quot;name&quot;:&quot;Детская одежда&quot;,&quot;section&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;Гардероб&quot;}},{&quot;id&quot;:4,&quot;name&quot;:&quot;Обувь и сумки&quot;,&quot;section&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;Гардероб&quot;}},{&quot;id&quot;:5,&quot;name&quot;:&quot;Аксессуары и украшения&quot;,&quot;section&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;Гардероб&quot;}}]}}.
        /// </summary>
        internal static string marketCategories {
            get {
                return ResourceManager.GetString("marketCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:3,&quot;items&quot;:[{&quot;id&quot;:198,&quot;owner_id&quot;:-43195721,&quot;title&quot;:&quot;Джинсовое платье &quot;,&quot;description&quot;:&quot;Размеры: S-M   (длина 78см)\nАрт 5429&quot;,&quot;price&quot;:{&quot;amount&quot;:&quot;235000&quot;,&quot;currency&quot;:{&quot;id&quot;:643,&quot;name&quot;:&quot;RUB&quot;},&quot;text&quot;:&quot;2 350 руб.&quot;},&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Женская одежда&quot;,&quot;section&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;Гардероб&quot;}},&quot;date&quot;:1441980511,&quot;thumb_photo&quot;:&quot;https:\/\/pp.vk.me\/c628418\/v628418464\/14220\/4OF9hyYuT9g.jpg&quot;,&quot;availability&quot;:0,&quot;albums_ids&quot;:[6],&quot;photos&quot;:[{&quot;id&quot;:379184674,&quot;album_id&quot;:-53,&quot;owner_id&quot;:-43195721,&quot;user_id&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string marketItemsList {
            get {
                return ResourceManager.GetString("marketItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:276,&quot;items&quot;:[{&quot;id&quot;:1127235,&quot;from_id&quot;:88832143,&quot;to_id&quot;:-65596623,&quot;date&quot;:1461189507,&quot;post_id&quot;:1126593,&quot;post_type&quot;:&quot;reply&quot;,&quot;text&quot;:&quot;[id16815310|Богдан], согласен а те кто говорит ты видел его камеру с плейстейшн и прочее если вы не знаете в китае есть люди которые за тебя сидят срок да и много где есть хорошого качества камеры)&quot;,&quot;post_source&quot;:{&quot;type&quot;:&quot;vk&quot;},&quot;comments&quot;:{&quot;count&quot;:0,&quot;can_post&quot;:1},&quot;likes&quot;:{&quot;count&quot;:0,&quot;user_likes&quot;:0,&quot;can_like&quot;:1,&quot;can_publish&quot;:1},&quot;reposts&quot;:{&quot;count&quot;:0,&quot;user_reposted&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mentionsItemsList {
            get {
                return ResourceManager.GetString("mentionsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:79771,&quot;items&quot;:[{&quot;id&quot;:147673,&quot;date&quot;:1461274931,&quot;out&quot;:1,&quot;user_id&quot;:127842370,&quot;read_state&quot;:0,&quot;title&quot;:&quot; ... &quot;,&quot;body&quot;:&quot;text&quot;,&quot;random_id&quot;:0,&quot;attachments&quot;:[{&quot;type&quot;:&quot;photo&quot;,&quot;photo&quot;:{&quot;id&quot;:410545563,&quot;album_id&quot;:-12,&quot;owner_id&quot;:-1,&quot;user_id&quot;:100,&quot;photo_75&quot;:&quot;https://pp.vk.me/...9bb/cC1ndaaUcag.jpg&quot;,&quot;photo_130&quot;:&quot;https://pp.vk.me/...9bc/4OoKxEUaaaE.jpg&quot;,&quot;photo_604&quot;:&quot;https://pp.vk.me/...9bd/Vz1oR972bIU.jpg&quot;,&quot;photo_807&quot;:&quot;https://pp.vk.me/...9be/Xpal8cOqSh8.jpg&quot;,&quot;photo_1280&quot;:&quot;https://pp.vk.me/...9bf/MBBQvMz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string messagesItemsList {
            get {
                return ResourceManager.GetString("messagesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;history&quot;:[[0,147672,0],[1,147672,1],[3,147672,-1,12345]],&quot;messages&quot;:{&quot;count&quot;:1,&quot;items&quot;:[{&quot;id&quot;:147672,&quot;date&quot;:1461273652,&quot;out&quot;:1,&quot;user_id&quot;:272282474,&quot;read_state&quot;:0,&quot;title&quot;:&quot; ... &quot;,&quot;body&quot;:&quot;text&quot;,&quot;random_id&quot;:0}]},&quot;profiles&quot;:[],&quot;new_pts&quot;:424197}}.
        /// </summary>
        internal static string messagesLongPollHistory {
            get {
                return ResourceManager.GetString("messagesLongPollHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;key&quot;:&quot;2e82f614c54b044118e165b20924c99f42b1affb&quot;,&quot;server&quot;:&quot;imv4.vk.com/im7310&quot;,&quot;ts&quot;:1769694030,&quot;pts&quot;:424197}}.
        /// </summary>
        internal static string messagesLongPollServer {
            get {
                return ResourceManager.GetString("messagesLongPollServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:2,&quot;items&quot;:[{&quot;id&quot;:24945500,&quot;first_name&quot;:&quot;Oleksandr&quot;,&quot;last_name&quot;:&quot;Dranko&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;domain&quot;:&quot;alexandrdranko&quot;,&quot;screen_name&quot;:&quot;alexandrdranko&quot;,&quot;bdate&quot;:&quot;24.8.1995&quot;,&quot;country&quot;:{&quot;id&quot;:160,&quot;title&quot;:&quot;Poland&quot;},&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c623127\/v623127500\/9103\/hflFz_g1jww.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c623127\/v623127500\/9102\/sUvSyUKcIrU.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c623127\/v623127500\/9101\/MJ4d5H1SG1k.jpg&quot;,&quot;photo_200_orig&quot;:&quot;https:\/\/pp.vk.me\/c623127\/v6231 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mixedProfilesList {
            get {
                return ResourceManager.GetString("mixedProfilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:16133651,&quot;common_friends&quot;:[29363547,31160235,34095918,159865266,272282474],&quot;common_count&quot;:5},{&quot;id&quot;:31160235,&quot;common_friends&quot;:[16133651,24945500,26300808,29363547,34095918,88318904,159865266],&quot;common_count&quot;:7}]}.
        /// </summary>
        internal static string mutualFriends {
            get {
                return ResourceManager.GetString("mutualFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;chat&quot;:{&quot;id&quot;:1,&quot;type&quot;:&quot;chat&quot;,&quot;title&quot;:&quot;олололо ок,да??&quot;,&quot;admin_id&quot;:16815310,&quot;users&quot;:[{&quot;id&quot;:16815310,&quot;first_name&quot;:&quot;Богдана&quot;,&quot;last_name&quot;:&quot;Штепана&quot;,&quot;sex&quot;:2,&quot;invited_by&quot;:16815310,&quot;type&quot;:&quot;profile&quot;}]},&quot;message_id&quot;:481516}}.
        /// </summary>
        internal static string newChatPhoto {
            get {
                return ResourceManager.GetString("newChatPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;items&quot;:[{&quot;type&quot;:&quot;video&quot;,&quot;source_id&quot;:-2682332,&quot;date&quot;:1461191133,&quot;video&quot;:{&quot;count&quot;:1,&quot;items&quot;:[{&quot;id&quot;:456239274,&quot;owner_id&quot;:-95012771,&quot;title&quot;:&quot;летящая дурилка.120&quot;,&quot;duration&quot;:2541,&quot;description&quot;:&quot;&quot;,&quot;date&quot;:1461190478,&quot;views&quot;:1,&quot;comments&quot;:0,&quot;photo_130&quot;:&quot;https:\/\/pp.vk.me\/c630230\/v630230771\/28d39\/0Qf3d2vLaHk.jpg&quot;,&quot;photo_320&quot;:&quot;https:\/\/pp.vk.me\/c630230\/v630230771\/28d37\/-7nIAN8FIoU.jpg&quot;,&quot;photo_800&quot;:&quot;https:\/\/pp.vk.me\/c630230\/v630230771\/28d36\/uB73ZaiQZGM.jpg&quot;,&quot;processing&quot;:1,&quot;can_add&quot;:1,&quot;can_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newsItemsList {
            get {
                return ResourceManager.GetString("newsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:3,&quot;items&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Музыка&quot;,&quot;no_reposts&quot;:1,&quot;source_ids&quot;:[-55657165,-50314780,-46231012,-45398514,-45019815,-44150176,-43666695,-43462544,-43296843,-42874211,-42743690,-42645487,-42467072,-41389591,-41131570,-40868077,-37202902,-33285665,-31339996,-30883877,-29420768,-29099541,-29033660,-29013286,-28849462,-27999076,-27380885,-26713338,-26068373,-24363586,-23420445,-20833574,-19453499,-15344106,-11751095,-10803616,-2469750,-111181,-9918,-1959]},{&quot;id&quot;:2,&quot;title&quot;:&quot;Кино&quot;},{&quot;id&quot;:3,&quot;ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newsLists {
            get {
                return ResourceManager.GetString("newsLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;id&quot;:11096473,&quot;owner_id&quot;:16815310,&quot;comments&quot;:0,&quot;read_comments&quot;:0,&quot;date&quot;:1307232484,&quot;title&quot;:&quot;Шесть уроков жизни&quot;,&quot;text&quot;:&quot;note html&quot;,&quot;view_url&quot;:&quot;https:\/\/m.vk.com\/note16815310_11096473?api_view=aefdd65530b7018afb41bfd429bf2f&quot;}}.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:4,&quot;items&quot;:[{&quot;id&quot;:11096473,&quot;owner_id&quot;:16815310,&quot;comments&quot;:0,&quot;read_comments&quot;:0,&quot;date&quot;:1307232484,&quot;title&quot;:&quot;Шесть уроков жизни&quot;,&quot;text&quot;:&quot;note html&quot;,&quot;view_url&quot;:&quot;https:\/\/m.vk.com\/note16815310_11096473?api_view=aefdd65530b7018afb41bfd429bf2f&quot;},{&quot;id&quot;:11096472,&quot;owner_id&quot;:16815310,&quot;comments&quot;:0,&quot;read_comments&quot;:0,&quot;date&quot;:1307232462,&quot;title&quot;:&quot;40 чисто женских моментов поведения&quot;,&quot;text&quot;:&quot;note html&quot;,&quot;view_url&quot;:&quot;https:\/\/m.vk.com\/note16815310_11096472?api_view=071a05479e61d8206b41b1a9189453&quot;},{&quot;id&quot;:1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string notesItemsList {
            get {
                return ResourceManager.GetString("notesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:1000,&quot;items&quot;:[{&quot;type&quot;:&quot;like_video&quot;,&quot;date&quot;:1461012203,&quot;parent&quot;:{&quot;id&quot;:168603708,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;Tiesto vs. Diplo - C&apos;mon (Piano Cover by linDdside)&quot;,&quot;duration&quot;:108,&quot;description&quot;:&quot;There is no music sheet. Made by ear. Enjoy!\n\n- because of rights infringement of the classroom where i recorded it, I&apos;ve felt obligated to hide the classroom -&quot;,&quot;date&quot;:1399152490,&quot;views&quot;:6,&quot;comments&quot;:0,&quot;photo_130&quot;:&quot;https:\/\/pp.vk.me\/c608519\/u16815310\/video\/s_8f5e8225.jpg&quot;,&quot;photo_320&quot;:&quot;https:\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;type&quot;:&quot;user&quot;,&quot;object_id&quot;: 16815310}}.
        /// </summary>
        internal static string objectInfo {
            get {
                return ResourceManager.GetString("objectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;id&quot;:230870814,&quot;thumb_id&quot;:0,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;Test Album&quot;,&quot;description&quot;:&apos;Test&apos;,&quot;created&quot;:1461013076,&quot;updated&quot;:1461013076,&quot;size&quot;:0,&quot;privacy_view&quot;:[&quot;friends&quot;],&quot;privacy_comment&quot;:[&quot;friends&quot;]}}.
        /// </summary>
        internal static string photoAlbum {
            get {
                return ResourceManager.GetString("photoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:8,&quot;items&quot;:[{&quot;id&quot;:230870814,&quot;thumb_id&quot;:0,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;Test Album&quot;,&quot;description&quot;:&quot;Test&quot;,&quot;created&quot;:1461013076,&quot;updated&quot;:1461013076,&quot;size&quot;:0,&quot;thumb_is_last&quot;:1,&quot;privacy_view&quot;:[&quot;friends&quot;],&quot;privacy_comment&quot;:[&quot;friends&quot;],&quot;sizes&quot;:[{&quot;src&quot;:&quot;https:\/\/vk.com\/images\/s_noalbum.png&quot;,&quot;width&quot;:75,&quot;height&quot;:55,&quot;type&quot;:&quot;s&quot;},{&quot;src&quot;:&quot;https:\/\/vk.com\/images\/m_noalbum.png&quot;,&quot;width&quot;:130,&quot;height&quot;:97,&quot;type&quot;:&quot;m&quot;},{&quot;src&quot;:&quot;https:\/\/vk.com\/images\/x_noalbum.png&quot;,&quot;width&quot;:432,&quot;height&quot;:249,&quot;type&quot;:&quot;x&quot;} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string photoAlbumsItemsList {
            get {
                return ResourceManager.GetString("photoAlbumsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:167,&quot;items&quot;:[{&quot;id&quot;:397256148,&quot;album_id&quot;:136414880,&quot;owner_id&quot;:16815310,&quot;sizes&quot;:[{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c633928\/v633928310\/8113\/j8GvxSFiozQ.jpg&quot;,&quot;width&quot;:87,&quot;height&quot;:130,&quot;type&quot;:&quot;m&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c633928\/v633928310\/8116\/BPsLFFM98Qw.jpg&quot;,&quot;width&quot;:130,&quot;height&quot;:194,&quot;type&quot;:&quot;o&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c633928\/v633928310\/8117\/kPngK-7AwuI.jpg&quot;,&quot;width&quot;:200,&quot;height&quot;:298,&quot;type&quot;:&quot;p&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c633928\/v633928310\/8118\/ziQdPfj_jfk.jpg&quot;,&quot;width&quot;:320,&quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string photosItemsList {
            get {
                return ResourceManager.GetString("photosItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:397256148,&quot;album_id&quot;:136414880,&quot;owner_id&quot;:16815310,&quot;sizes&quot;:[{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c633928\/v633928310\/8113\/j8GvxSFiozQ.jpg&quot;,&quot;width&quot;:87,&quot;height&quot;:130,&quot;type&quot;:&quot;m&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c633928\/v633928310\/8116\/BPsLFFM98Qw.jpg&quot;,&quot;width&quot;:130,&quot;height&quot;:194,&quot;type&quot;:&quot;o&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c633928\/v633928310\/8117\/kPngK-7AwuI.jpg&quot;,&quot;width&quot;:200,&quot;height&quot;:298,&quot;type&quot;:&quot;p&quot;},{&quot;src&quot;:&quot;https:\/\/pp.vk.me\/c633928\/v633928310\/8118\/ziQdPfj_jfk.jpg&quot;,&quot;width&quot;:320,&quot;height&quot;:477,&quot;type&quot;:&quot;q&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string photosList {
            get {
                return ResourceManager.GetString("photosList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;upload_url&quot;:&quot;some_upload_url&quot;,&quot;album_id&quot;:1234,&quot;user_id&quot;:12345}}.
        /// </summary>
        internal static string photosUploadServer {
            get {
                return ResourceManager.GetString("photosUploadServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:42830775,&quot;user_id&quot;:3420,&quot;placer_id&quot;:46775,&quot;tagged_name&quot;:&quot;Georgy Lobushkin&quot;,&quot;date&quot;:1413100329,&quot;x&quot;:45.16,&quot;y&quot;:42.97,&quot;x2&quot;:59.22,&quot;y2&quot;:63.75,&quot;viewed&quot;:0},{&quot;id&quot;:42830777,&quot;user_id&quot;:9256,&quot;placer_id&quot;:46775,&quot;tagged_name&quot;:&quot;Dmitry Vanyukov&quot;,&quot;date&quot;:1413100353,&quot;x&quot;:51.56,&quot;y&quot;:34.84,&quot;x2&quot;:56.25,&quot;y2&quot;:39.53,&quot;viewed&quot;:1}]}.
        /// </summary>
        internal static string photoTags {
            get {
                return ResourceManager.GetString("photoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;id&quot;:1234}}.
        /// </summary>
        internal static string placeAdd {
            get {
                return ResourceManager.GetString("placeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:1999,&quot;items&quot;:[{&quot;id&quot;:213784,&quot;title&quot;:&quot;Дом Зингера&quot;,&quot;latitude&quot;:59.935624,&quot;longitude&quot;:30.325875,&quot;created&quot;:1295369575,&quot;icon&quot;:&quot;https:\/\/vk.com\/images\/places\/work.png&quot;,&quot;checkins&quot;:415,&quot;updated&quot;:1460883258,&quot;type&quot;:2,&quot;country&quot;:1,&quot;city&quot;:2,&quot;address&quot;:&quot;Невский проспект 28&quot;,&quot;distance&quot;:3},{&quot;id&quot;:4348949,&quot;title&quot;:&quot;Штаб ВКонтакте&quot;,&quot;latitude&quot;:59.935620,&quot;longitude&quot;:30.325884,&quot;created&quot;:1356787551,&quot;icon&quot;:&quot;https:\/\/vk.com\/images\/places\/place.png&quot;,&quot;group_id&quot;:47590230,&quot;group_photo&quot;:&quot;https:\/\/pp.vk.me\/c40 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string placesItemsList {
            get {
                return ResourceManager.GetString("placesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:4980426,&quot;title&quot;:&quot;test&quot;,&quot;latitude&quot;:25.000000,&quot;longitude&quot;:25.000000,&quot;created&quot;:1364117621,&quot;icon&quot;:&quot;https:\/\/vk.com\/images\/places\/home.png&quot;,&quot;checkins&quot;:33,&quot;updated&quot;:1460612881,&quot;type&quot;:1},{&quot;id&quot;:1,&quot;title&quot;:&quot;Baila Baila&quot;,&quot;latitude&quot;:55.657941,&quot;longitude&quot;:37.751574,&quot;created&quot;:1280741941,&quot;icon&quot;:&quot;https:\/\/vk.com\/images\/places\/clubs.png&quot;,&quot;checkins&quot;:436,&quot;updated&quot;:1459540482,&quot;type&quot;:4,&quot;country&quot;:1,&quot;city&quot;:1,&quot;address&quot;:&quot;Мячковский б-р 3а&quot;},{&quot;id&quot;:43252,&quot;title&quot;:&quot;Phoenix Litchfield Municipal Airport&quot;,&quot;latit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string placesList {
            get {
                return ResourceManager.GetString("placesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;Дом&quot;,&quot;icon&quot;:&quot;https:\/\/vk.com\/images\/places\/home.png&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;Работа&quot;,&quot;icon&quot;:&quot;https:\/\/vk.com\/images\/places\/work.png&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;Ресторан&quot;,&quot;icon&quot;:&quot;https:\/\/vk.com\/images\/places\/restaraunt.png&quot;},{&quot;id&quot;:4,&quot;title&quot;:&quot;Клуб&quot;,&quot;icon&quot;:&quot;https:\/\/vk.com\/images\/places\/clubs.png&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;Кинотеатр&quot;,&quot;icon&quot;:&quot;https:\/\/vk.com\/images\/places\/cinema.png&quot;},{&quot;id&quot;:6,&quot;title&quot;:&quot;Бар&quot;,&quot;icon&quot;:&quot;https:\/\/vk.com\/images\/places\/bar.png&quot;},{&quot;id&quot;:7,&quot;title&quot;:&quot;Развлечен [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string placeTypes {
            get {
                return ResourceManager.GetString("placeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;owner_id&quot;:-26406986,&quot;poll_id&quot;:222496894,&quot;created&quot;:1460316481,&quot;question&quot;:&quot;Насколько ловкие твои руки?&quot;,&quot;votes&quot;:3911,&quot;answer_id&quot;:0,&quot;answers&quot;:[{&quot;id&quot;:739902439,&quot;text&quot;:&quot;Да, умею. Правда на это уходит времени больше, чем на поиски смысла жизни.&quot;,&quot;votes&quot;:401,&quot;rate&quot;:10.250000},{&quot;id&quot;:739902440,&quot;text&quot;:&quot;Легко, по фасту собираю.&quot;,&quot;votes&quot;:233,&quot;rate&quot;:5.960000},{&quot;id&quot;:739902441,&quot;text&quot;:&quot;Собираю ногами, с закрытыми глазами, после 10 кужек пива.&quot;,&quot;votes&quot;:126,&quot;rate&quot;:3.220000},{&quot;id&quot;:739902442,&quot;text&quot;:&quot;Две грани соб [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poll {
            get {
                return ResourceManager.GetString("poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;answer_id&quot;:739946640,&quot;users&quot;:{&quot;count&quot;:1,&quot;items&quot;:[{&quot;id&quot;:16815310,&quot;first_name&quot;:&quot;Богдан&quot;,&quot;last_name&quot;:&quot;Штепан&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;screen_name&quot;:&quot;virtyaluk&quot;}]}},{&quot;answer_id&quot;:739946641,&quot;users&quot;:{&quot;count&quot;:2,&quot;items&quot;:[{&quot;id&quot;:178250508,&quot;first_name&quot;:&quot;Вася&quot;,&quot;last_name&quot;:&quot;Пупкин&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;screen_name&quot;:&quot;make_the_crowd_go&quot;},{&quot;id&quot;:127842370,&quot;first_name&quot;:&quot;Владислав&quot;,&quot;last_name&quot;:&quot;Брин&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;screen_name&quot;:&quot;id127842370&quot;}]}},{&quot;answer_id&quot;:739946642,&quot;users&quot;:{&quot;count&quot;:0,&quot;items&quot;:[]}}]}.
        /// </summary>
        internal static string pollVoters {
            get {
                return ResourceManager.GetString("pollVoters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;reach_subscribers&quot;:11385,&quot;reach_total&quot;:21105,&quot;links&quot;:92,&quot;to_group&quot;:97,&quot;join_group&quot;:3,&quot;report&quot;:0,&quot;hide&quot;:58,&quot;unsubscribe&quot;:15}}.
        /// </summary>
        internal static string postReach {
            get {
                return ResourceManager.GetString("postReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:6499,&quot;items&quot;:[{&quot;id&quot;:8226,&quot;from_id&quot;:16815310,&quot;owner_id&quot;:16815310,&quot;date&quot;:1460845707,&quot;post_type&quot;:&quot;post&quot;,&quot;text&quot;:&quot;test&quot;,&quot;can_edit&quot;:1,&quot;can_delete&quot;:1,&quot;can_pin&quot;:1,&quot;attachments&quot;:[{&quot;type&quot;:&quot;photo&quot;,&quot;photo&quot;:{&quot;id&quot;:412644711,&quot;album_id&quot;:-7,&quot;owner_id&quot;:16815310,&quot;photo_75&quot;:&quot;https:\/\/pp.vk.me\/c636031\/v636031972\/17f9\/zqw_nq2GXb0.jpg&quot;,&quot;photo_130&quot;:&quot;https:\/\/pp.vk.me\/c636031\/v636031972\/17fa\/wUHAhbg2Nhk.jpg&quot;,&quot;photo_604&quot;:&quot;https:\/\/pp.vk.me\/c636031\/v636031972\/17fb\/VjYcTHsPtoE.jpg&quot;,&quot;width&quot;:604,&quot;heig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string postsItemsList {
            get {
                return ResourceManager.GetString("postsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;first_name&quot;:&quot;Богдан&quot;,&quot;last_name&quot;:&quot;Штепан&quot;,&quot;screen_name&quot;:&quot;virtyaluk&quot;,&quot;sex&quot;:2,&quot;relation&quot;:0,&quot;bdate&quot;:&quot;29.2.0&quot;,&quot;bdate_visibility&quot;:2,&quot;home_town&quot;:&quot;&quot;,&quot;status&quot;:&quot;Together We Are&quot;,&quot;phone&quot;:&quot;+380 **** * ** 52&quot;,&quot;name_request&quot;:{&quot;id&quot;:12345,&quot;status&quot;:&quot;processing&quot;,&quot;first_name&quot;:&quot;Bohdan&quot;,&quot;last_name&quot;:&quot;Shtepan&quot;}}}.
        /// </summary>
        internal static string profileInfo {
            get {
                return ResourceManager.GetString("profileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:6,&quot;items&quot;:[{&quot;id&quot;:16133651,&quot;first_name&quot;:&quot;Vitalik&quot;,&quot;last_name&quot;:&quot;Ulybin&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;domain&quot;:&quot;ylubin&quot;,&quot;screen_name&quot;:&quot;ylubin&quot;,&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10feb\/bemQ80NlFWM.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fea\/5xmjTRE-1Bg.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe9\/BInBMF-GmS8.jpg&quot;,&quot;photo_200_orig&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe7\/sHgM2UkEh2o.jpg&quot;,&quot;has_mobile&quot;:1,&quot;wall_comments&quot;:0,&quot;can_post [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string profilesMixedList {
            get {
                return ResourceManager.GetString("profilesMixedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:83,&quot;items&quot;:[{&quot;id&quot;:1000001,&quot;title&quot;:&quot;Адыгея&quot;},{&quot;id&quot;:1121540,&quot;title&quot;:&quot;Алтай&quot;},{&quot;id&quot;:1121829,&quot;title&quot;:&quot;Алтайский край&quot;},{&quot;id&quot;:1123488,&quot;title&quot;:&quot;Амурская область&quot;},{&quot;id&quot;:1000236,&quot;title&quot;:&quot;Архангельская область&quot;}]}}.
        /// </summary>
        internal static string regionsItemsList {
            get {
                return ResourceManager.GetString("regionsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:1,&quot;items&quot;:[{&quot;user_id&quot;:224586038,&quot;from&quot;:&apos;178250508&apos;,&quot;mutual&quot;:{&quot;count&quot;:1,&quot;users&quot;:[178250508]}}]}}.
        /// </summary>
        internal static string requestsItemsList {
            get {
                return ResourceManager.GetString("requestsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:0}.
        /// </summary>
        internal static string responseFalse {
            get {
                return ResourceManager.GetString("responseFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:481516}.
        /// </summary>
        internal static string responseNum {
            get {
                return ResourceManager.GetString("responseNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[12345,-54321,1,-2]}.
        /// </summary>
        internal static string responseNumsList {
            get {
                return ResourceManager.GetString("responseNumsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:&quot;some text&quot;}.
        /// </summary>
        internal static string responseText {
            get {
                return ResourceManager.GetString("responseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:1}.
        /// </summary>
        internal static string responseTrue {
            get {
                return ResourceManager.GetString("responseTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;photo_hash&quot;:&quot;hash&quot;,&quot;photo_src&quot;:&quot;src&quot;}}.
        /// </summary>
        internal static string saveOwnerPhoto {
            get {
                return ResourceManager.GetString("saveOwnerPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:3211,&quot;items&quot;:[{&quot;id&quot;:8243,&quot;title&quot;:&quot;Anglo-American School of Moscow&quot;},{&quot;id&quot;:5780,&quot;title&quot;:&quot;Anglo-Russian School 497&quot;},{&quot;id&quot;:1669882,&quot;title&quot;:&quot;English International School Moscow&quot;},{&quot;id&quot;:1687981,&quot;title&quot;:&quot;Авиационная школа «Гамаюн»&quot;},{&quot;id&quot;:1706632,&quot;title&quot;:&quot;Авиационная школа Аэрофлота&quot;}]}}.
        /// </summary>
        internal static string schoolsItemsList {
            get {
                return ResourceManager.GetString("schoolsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:33,&quot;type&quot;:&quot;chat&quot;,&quot;title&quot;:&quot;FooBar&quot;,&quot;admin_id&quot;:16815310,&quot;users&quot;:[16815310,127842370,156830612,178250508,-2058651603],&quot;photo_50&quot;:&quot;https://pp.vk.me/...093/4KZJBsyqBdk.jpg&quot;,&quot;photo_100&quot;:&quot;https://pp.vk.me/...092/cu9Dki7nhwM.jpg&quot;,&quot;photo_200&quot;:&quot;https://pp.vk.me/...091/gFVio0ElsTQ.jpg&quot;},{&quot;type&quot;:&quot;profile&quot;,&quot;id&quot;:156830612,&quot;first_name&quot;:&quot;Alexander&quot;,&quot;last_name&quot;:&quot;Kymirov&quot;}]}.
        /// </summary>
        internal static string searchDialogs {
            get {
                return ResourceManager.GetString("searchDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;type&quot;:&quot;profile&quot;,&quot;section&quot;:&quot;friends&quot;,&quot;description&quot;:&quot;Ukraine&quot;,&quot;profile&quot;:{&quot;id&quot;:24945500,&quot;first_name&quot;:&quot;Oleksandr&quot;,&quot;last_name&quot;:&quot;Dranko&quot;,&quot;sex&quot;:2}},{&quot;type&quot;:&quot;group&quot;,&quot;section&quot;:&quot;publics&quot;,&quot;description&quot;:&quot;СМИ, 13 718 подписчиков&quot;,&quot;group&quot;:{&quot;id&quot;:69019591,&quot;name&quot;:&quot;EPSCAPE | Новости сериалов и кино&quot;,&quot;screen_name&quot;:&quot;epscape&quot;,&quot;is_closed&quot;:0,&quot;type&quot;:&quot;page&quot;,&quot;is_admin&quot;:0,&quot;is_member&quot;:1,&quot;photo_50&quot;:&quot;https://pp.vk.me/...5f9/r5NWq655vsg.jpg&quot;,&quot;photo_100&quot;:&quot;https://pp.vk.me/...5f8/bDhZC3CyA54.jpg&quot;,&quot;photo_200&quot;:&quot;https://pp.vk.m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string searchHints {
            get {
                return ResourceManager.GetString("searchHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:2,&quot;groups&quot;:[{&quot;id&quot;:65596623,&quot;name&quot;:&quot;FTP&quot;,&quot;screen_name&quot;:&quot;ftp78&quot;,&quot;is_closed&quot;:0,&quot;type&quot;:&quot;page&quot;,&quot;description&quot;:&quot;Чёрный юмор&quot;,&quot;members_count&quot;:341049,&quot;start_date&quot;:19450509,&quot;can_post&quot;:0,&quot;can_see_all_posts&quot;:1,&quot;activity&quot;:&quot;Art and entertainment&quot;,&quot;status&quot;:&quot;иди сюда&quot;,&quot;contacts&quot;:[{&quot;user_id&quot;:171605462,&quot;desc&quot;:&quot;Агент по рекламе &quot;},{&quot;user_id&quot;:313566042,&quot;desc&quot;:&quot;только Реклама . вп не делаем &quot;},{&quot;user_id&quot;:236428820}],&quot;can_upload_doc&quot;:0,&quot;can_upload_video&quot;:0,&quot;can_create_topic&quot;:0,&quot;fixed_post&quot;:1063983,&quot;verified&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string separatedProfilesList {
            get {
                return ResourceManager.GetString("separatedProfilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:1460247613}.
        /// </summary>
        internal static string serverTime {
            get {
                return ResourceManager.GetString("serverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;state_code&quot;:1,&quot;state&quot;:&quot;ok&quot;}}.
        /// </summary>
        internal static string setCallbackServer {
            get {
                return ResourceManager.GetString("setCallbackServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;changed&quot;:1,&quot;name_request&quot;:{&quot;id&quot;:12345,&quot;status&quot;:&quot;processing&quot;,&quot;first_name&quot;:&quot;Bohdan&quot;,&quot;last_name&quot;:&quot;Shtepan&quot;}}}.
        /// </summary>
        internal static string setProfileInfo {
            get {
                return ResourceManager.GetString("setProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;day&quot;:&quot;2016-04-17&quot;,&quot;views&quot;:2402,&quot;visitors&quot;:1817,&quot;reach&quot;:1043,&quot;reach_subscribers&quot;:219,&quot;subscribed&quot;:86,&quot;unsubscribed&quot;:70,&quot;sex&quot;:[{&quot;visitors&quot;:735,&quot;value&quot;:&quot;f&quot;},{&quot;visitors&quot;:756,&quot;value&quot;:&quot;m&quot;}],&quot;age&quot;:[{&quot;visitors&quot;:406,&quot;value&quot;:&quot;12-18&quot;},{&quot;visitors&quot;:261,&quot;value&quot;:&quot;18-21&quot;},{&quot;visitors&quot;:176,&quot;value&quot;:&quot;21-24&quot;},{&quot;visitors&quot;:143,&quot;value&quot;:&quot;24-27&quot;},{&quot;visitors&quot;:90,&quot;value&quot;:&quot;27-30&quot;},{&quot;visitors&quot;:73,&quot;value&quot;:&quot;30-35&quot;},{&quot;visitors&quot;:44,&quot;value&quot;:&quot;35-45&quot;},{&quot;visitors&quot;:81,&quot;value&quot;:&quot;45-100&quot;}],&quot;sex_age&quot;:[{&quot;visitors&quot;:254,&quot;value&quot;:&quot;f;12-18&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stats {
            get {
                return ResourceManager.GetString("stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;key&quot;:&quot;foo&quot;,&quot;value&quot;:&quot;bar&quot;}]}.
        /// </summary>
        internal static string storageValsList {
            get {
                return ResourceManager.GetString("storageValsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:1,&quot;title&quot;:&quot;8 Марта ул.&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;А\/Д Подъезд к а. Гатлукай дор.&quot;},{&quot;id&quot;:3,&quot;title&quot;:&quot;А\/Д Подъезд к г. Адыгейску дор.&quot;},{&quot;id&quot;:4,&quot;title&quot;:&quot;А\/Д Подъезд к ж\/д станции Псекупс дор.&quot;},{&quot;id&quot;:5,&quot;title&quot;:&quot;А\/Д Пчегатлукай-Гатлукай-Адыгейск дор.&quot;}]}.
        /// </summary>
        internal static string streetsList {
            get {
                return ResourceManager.GetString("streetsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[&quot;foo&quot;,&quot;bar&quot;,&quot;baz&quot;]}.
        /// </summary>
        internal static string stringsList {
            get {
                return ResourceManager.GetString("stringsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:80,&quot;items&quot;:[{&quot;id&quot;:21972158,&quot;title&quot;:&quot;Вопросы по поводу создания приложений&quot;,&quot;created&quot;:1260720340,&quot;created_by&quot;:189814,&quot;updated&quot;:1460560838,&quot;updated_by&quot;:239489016,&quot;is_closed&quot;:0,&quot;is_fixed&quot;:1,&quot;comments&quot;:20490},{&quot;id&quot;:21972169,&quot;title&quot;:&quot;Замеченные ошибки в API или документации&quot;,&quot;created&quot;:1260720510,&quot;created_by&quot;:189814,&quot;updated&quot;:1363956097,&quot;updated_by&quot;:189814,&quot;is_closed&quot;:1,&quot;is_fixed&quot;:1,&quot;comments&quot;:3747},{&quot;id&quot;:27042222,&quot;title&quot;:&quot;Обновлённый платежный API для приложений&quot;,&quot;created&quot;:1348220340,&quot;create [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string topicItemsList {
            get {
                return ResourceManager.GetString("topicItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:7,&quot;items&quot;:[{&quot;id&quot;:1,&quot;name&quot;:&quot;Текстовые&quot;,&quot;count&quot;:21},{&quot;id&quot;:2,&quot;name&quot;:&quot;Архивы&quot;,&quot;count&quot;:10},{&quot;id&quot;:3,&quot;name&quot;:&quot;Анимации&quot;,&quot;count&quot;:257},{&quot;id&quot;:4,&quot;name&quot;:&quot;Изображения&quot;,&quot;count&quot;:26},{&quot;id&quot;:5,&quot;name&quot;:&quot;Музыка&quot;,&quot;count&quot;:1},{&quot;id&quot;:6,&quot;name&quot;:&quot;Видео&quot;,&quot;count&quot;:1},{&quot;id&quot;:8,&quot;name&quot;:&quot;Прочие&quot;,&quot;count&quot;:459}]}}.
        /// </summary>
        internal static string typesItemsList {
            get {
                return ResourceManager.GetString("typesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:702,&quot;items&quot;:[{&quot;id&quot;:2,&quot;title&quot;:&quot;МГУ&quot;},{&quot;id&quot;:86,&quot;title&quot;:&quot;АПИ при ИГиП РАН&quot;},{&quot;id&quot;:87,&quot;title&quot;:&quot;Финансовый университет (бывш. ГУМФ)&quot;},{&quot;id&quot;:88,&quot;title&quot;:&quot;АГПС МЧС России&quot;},{&quot;id&quot;:89,&quot;title&quot;:&quot;АГЗ МЧС России&quot;}]}}.
        /// </summary>
        internal static string universitiesItemsList {
            get {
                return ResourceManager.GetString("universitiesItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;upload_url&quot;:&quot;some_upload_url&quot;}}.
        /// </summary>
        internal static string uploadServer {
            get {
                return ResourceManager.GetString("uploadServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;online&quot;:1,&quot;time&quot;:1461276600}}.
        /// </summary>
        internal static string userLastActivity {
            get {
                return ResourceManager.GetString("userLastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:3,&quot;items&quot;:[{&quot;id&quot;:16133651,&quot;first_name&quot;:&quot;Vitalik&quot;,&quot;last_name&quot;:&quot;Ulybin&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;domain&quot;:&quot;ylubin&quot;,&quot;screen_name&quot;:&quot;ylubin&quot;,&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10feb\/bemQ80NlFWM.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fea\/5xmjTRE-1Bg.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe9\/BInBMF-GmS8.jpg&quot;,&quot;photo_200_orig&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe7\/sHgM2UkEh2o.jpg&quot;,&quot;has_mobile&quot;:1,&quot;wall_comments&quot;:0,&quot;can_post [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usersItemsList {
            get {
                return ResourceManager.GetString("usersItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:16133651,&quot;first_name&quot;:&quot;Vitalik&quot;,&quot;last_name&quot;:&quot;Ulybin&quot;,&quot;sex&quot;:2,&quot;nickname&quot;:&quot;&quot;,&quot;domain&quot;:&quot;ylubin&quot;,&quot;screen_name&quot;:&quot;ylubin&quot;,&quot;photo_50&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10feb\/bemQ80NlFWM.jpg&quot;,&quot;photo_100&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fea\/5xmjTRE-1Bg.jpg&quot;,&quot;photo_200&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe9\/BInBMF-GmS8.jpg&quot;,&quot;photo_200_orig&quot;:&quot;https:\/\/pp.vk.me\/c633323\/v633323651\/10fe7\/sHgM2UkEh2o.jpg&quot;,&quot;has_mobile&quot;:1,&quot;wall_comments&quot;:0,&quot;can_post&quot;:0,&quot;can_see_all_po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usersList {
            get {
                return ResourceManager.GetString("usersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;online&quot;:[25290020,31160235,34095918,66475294],&quot;online_mobile&quot;:[16133651,24945500]}}.
        /// </summary>
        internal static string usersOnline {
            get {
                return ResourceManager.GetString("usersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;text&quot;:&quot;Major Lazer x Showtek – I’m a Believer&quot;,&quot;audio&quot;:{&quot;id&quot;:456239425,&quot;owner_id&quot;:16815310,&quot;artist&quot;:&quot;Major Lazer x Showtek&quot;,&quot;title&quot;:&quot;I’m a Believer&quot;,&quot;duration&quot;:254,&quot;date&quot;:1460392491,&quot;url&quot;:&quot;https : //cs7-5v4.v...c7EHzS9BZw1y1TWZ48c&quot;,&quot;genre_id&quot;:18,&quot;no_search&quot;:1}}}.
        /// </summary>
        internal static string userStatus {
            get {
                return ResourceManager.GetString("userStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;album_id&quot;:1234}}.
        /// </summary>
        internal static string videoAddAlbum {
            get {
                return ResourceManager.GetString("videoAddAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;id&quot;:38887239,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;test&quot;,&quot;count&quot;:1,&quot;photo_320&quot;:&quot;https:\/\/pp.vk.me\/c633524\/u50013393\/video\/l_cb5ee969.jpg&quot;,&quot;photo_160&quot;:&quot;https:\/\/pp.vk.me\/c633524\/u50013393\/video\/m_055fec62.jpg&quot;,&quot;updated_time&quot;:1458066164,&quot;privacy&quot;:[&quot;only_me&quot;]}}.
        /// </summary>
        internal static string videoAlbum {
            get {
                return ResourceManager.GetString("videoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:5,&quot;items&quot;:[{&quot;id&quot;:38887239,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;test&quot;,&quot;count&quot;:1,&quot;photo_320&quot;:&quot;https:\/\/pp.vk.me\/c633524\/u50013393\/video\/l_cb5ee969.jpg&quot;,&quot;photo_160&quot;:&quot;https:\/\/pp.vk.me\/c633524\/u50013393\/video\/m_055fec62.jpg&quot;,&quot;updated_time&quot;:1458066164,&quot;privacy&quot;:[&quot;only_me&quot;]},{&quot;id&quot;:38887238,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;wtf&quot;,&quot;count&quot;:1,&quot;photo_320&quot;:&quot;https:\/\/pp.vk.me\/c622418\/u551488\/video\/l_9da88abe.jpg&quot;,&quot;photo_160&quot;:&quot;https:\/\/pp.vk.me\/c622418\/u551488\/video\/m_c73a125d.jpg&quot;,&quot;updated_tim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string videoAlbumsItemsList {
            get {
                return ResourceManager.GetString("videoAlbumsItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;items&quot;:[{&quot;items&quot;:[{&quot;id&quot;:456239073,&quot;owner_id&quot;:-25988584,&quot;title&quot;:&quot;Таку Секине в гостях у «Еды»&quot;,&quot;duration&quot;:389,&quot;description&quot;:&quot;&quot;,&quot;date&quot;:1460801976,&quot;views&quot;:7623,&quot;comments&quot;:8,&quot;photo_130&quot;:&quot;https:\/\/cs7065.vk.me\/c636328\/v636328584\/19ae\/L132LsR0hYI.jpg&quot;,&quot;photo_320&quot;:&quot;https:\/\/cs7065.vk.me\/c636328\/v636328584\/19ac\/Q0yo6gkjbTk.jpg&quot;,&quot;photo_800&quot;:&quot;https:\/\/cs7065.vk.me\/c636328\/v636328584\/19ab\/1ERvshMCDmw.jpg&quot;,&quot;can_add&quot;:1,&quot;type&quot;:&quot;video&quot;},{&quot;id&quot;:456239072,&quot;owner_id&quot;:-25988584,&quot;title&quot;:&quot;«Олд-фэшенд [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string videoCatalog {
            get {
                return ResourceManager.GetString("videoCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;items&quot;:[{&quot;type&quot;:&quot;album&quot;,&quot;id&quot;:38887239,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;test&quot;,&quot;count&quot;:1,&quot;photo_320&quot;:&quot;https:\/\/pp.vk.me\/c633524\/u50013393\/video\/l_cb5ee969.jpg&quot;,&quot;photo_160&quot;:&quot;https:\/\/pp.vk.me\/c633524\/u50013393\/video\/m_055fec62.jpg&quot;,&quot;updated_time&quot;:1458066164,&quot;privacy&quot;:[&quot;only_me&quot;]},{&quot;type&quot;:&quot;video&quot;,&quot;id&quot;:167787241,&quot;owner_id&quot;:-63858240,&quot;title&quot;:&quot;Когда звонит бывшая (Vine)&quot;,&quot;duration&quot;:6,&quot;description&quot;:&quot;&quot;,&quot;date&quot;:1395074446,&quot;views&quot;:254834,&quot;comments&quot;:75,&quot;photo_130&quot;:&quot;https:\/\/pp.vk.me\/c532519\/u24057 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string videoCatalogSection {
            get {
                return ResourceManager.GetString("videoCatalogSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;upload_url&quot;:&quot;https://cs505217....fupload=1&amp;api=1&quot;,&quot;video_id&quot;:456239067,&quot;owner_id&quot;:16815310,&quot;title&quot;:&quot;No name&quot;,&quot;description&quot;:&quot;&quot;,&quot;access_key&quot;:&quot;e8a1325ae87fb901b6&quot;}}.
        /// </summary>
        internal static string videoSave {
            get {
                return ResourceManager.GetString("videoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;count&quot;:4597,&quot;items&quot;:[{&quot;id&quot;:167787241,&quot;owner_id&quot;:-63858240,&quot;title&quot;:&quot;Когда звонит бывшая (Vine)&quot;,&quot;duration&quot;:6,&quot;description&quot;:&quot;&quot;,&quot;date&quot;:1395074446,&quot;views&quot;:254834,&quot;comments&quot;:75,&quot;photo_130&quot;:&quot;https:\/\/pp.vk.me\/c532519\/u240579991\/video\/s_9a1b2abd.jpg&quot;,&quot;photo_320&quot;:&quot;https:\/\/pp.vk.me\/c532519\/u240579991\/video\/l_d091a6ee.jpg&quot;,&quot;adding_date&quot;:1460931140,&quot;user_id&quot;:182956644,&quot;player&quot;:&quot;https:\/\/vk.com\/video_ext.php?oid=-63858240&amp;id=167787241&amp;hash=3023bc2767fd485d&amp;__ref=vk.api&amp;api_hash=14609325446dee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string videosItemsList {
            get {
                return ResourceManager.GetString("videosItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;user_id&quot;:9594917,&quot;tag_id&quot;:88134675,&quot;placer_id&quot;:57193514,&quot;tagged_name&quot;:&quot;Маринка Юзефович&quot;,&quot;date&quot;:1267692441,&quot;viewed&quot;:1},{&quot;user_id&quot;:11511140,&quot;tag_id&quot;:88134678,&quot;placer_id&quot;:57193514,&quot;tagged_name&quot;:&quot;Людмилочка Ткаченко&quot;,&quot;date&quot;:1267692455,&quot;viewed&quot;:0}]}.
        /// </summary>
        internal static string videoTags {
            get {
                return ResourceManager.GetString("videoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;post_id&quot;:1234,&quot;success&quot;:1,&quot;reposts_count&quot;:50,&quot;likes_count&quot;:105}}.
        /// </summary>
        internal static string wallPost {
            get {
                return ResourceManager.GetString("wallPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:183526239,&quot;length&quot;:23,&quot;date&quot;:1430756719,&quot;editor_id&quot;:2314852,&quot;editor_name&quot;:&quot;Irina Denezhkina&quot;}]}.
        /// </summary>
        internal static string wikiHistory {
            get {
                return ResourceManager.GetString("wikiHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;id&quot;:48646066,&quot;group_id&quot;:79831840,&quot;title&quot;:&quot;book&quot;,&quot;who_can_view&quot;:2,&quot;who_can_edit&quot;:0,&quot;edited&quot;:1418760747,&quot;created&quot;:1416349779,&quot;views&quot;:470,&quot;source&quot;:&quot;156 книг для IT-профессионалов&quot;,&quot;view_url&quot;:&quot;https : //m.vk.com/...ed7580b41b51f2208cd&quot;}}.
        /// </summary>
        internal static string wikiPage {
            get {
                return ResourceManager.GetString("wikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;id&quot;:48646066,&quot;title&quot;:&quot;book&quot;,&quot;group_id&quot;:79831840,&quot;created&quot;:1416349779,&quot;edited&quot;:1418760747,&quot;who_can_view&quot;:2,&quot;who_can_edit&quot;:0,&quot;views&quot;:470},{&quot;id&quot;:48646082,&quot;title&quot;:&quot;goldfondbook&quot;,&quot;group_id&quot;:79831840,&quot;created&quot;:1416350500,&quot;edited&quot;:1416429170,&quot;who_can_view&quot;:2,&quot;who_can_edit&quot;:0,&quot;views&quot;:306},{&quot;id&quot;:49674033,&quot;title&quot;:&quot;Задачи C&quot;,&quot;group_id&quot;:79831840,&quot;created&quot;:1444683925,&quot;edited&quot;:1444683925,&quot;who_can_view&quot;:2,&quot;who_can_edit&quot;:0,&quot;views&quot;:0},{&quot;id&quot;:49674057,&quot;title&quot;:&quot;лекция 3&quot;,&quot;group_id&quot;:79831840,&quot;created&quot;:1444684154, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wikiTitles {
            get {
                return ResourceManager.GetString("wikiTitles", resourceCulture);
            }
        }
    }
}
